// Code generated by protoc-gen-go.
// source: google/cloud/dialogflow/v2beta1/entity_type.proto
// DO NOT EDIT!

/*
Package dialogflow is a generated protocol buffer package.

It is generated from these files:
	google/cloud/dialogflow/v2beta1/entity_type.proto

It has these top-level messages:
	EntityType
	ListEntityTypesRequest
	ListEntityTypesResponse
	GetEntityTypeRequest
	CreateEntityTypeRequest
	UpdateEntityTypeRequest
	DeleteEntityTypeRequest
	BatchUpdateEntityTypesRequest
	BatchUpdateEntityTypesResponse
	BatchDeleteEntityTypesRequest
	BatchCreateEntitiesRequest
	BatchUpdateEntitiesRequest
	BatchDeleteEntitiesRequest
	EntityTypeBatch
*/
package dialogflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_longrunning "google.golang.org/genproto/googleapis/longrunning"
import google_protobuf2 "github.com/golang/protobuf/ptypes/empty"
import google_protobuf3 "google.golang.org/genproto/protobuf/field_mask"
import _ "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Represents kinds of entities.
type EntityType_Kind int32

const (
	// Not specified. This value should be never used.
	EntityType_KIND_UNSPECIFIED EntityType_Kind = 0
	// Map entity types allow mapping of a group of synonyms to a canonical
	// value.
	EntityType_KIND_MAP EntityType_Kind = 1
	// List entity types contain a set of entries that do not map to canonical
	// values. However, list entity types can contain references to other entity
	// types (with or without aliases).
	EntityType_KIND_LIST EntityType_Kind = 2
)

var EntityType_Kind_name = map[int32]string{
	0: "KIND_UNSPECIFIED",
	1: "KIND_MAP",
	2: "KIND_LIST",
}
var EntityType_Kind_value = map[string]int32{
	"KIND_UNSPECIFIED": 0,
	"KIND_MAP":         1,
	"KIND_LIST":        2,
}

func (x EntityType_Kind) String() string {
	return proto.EnumName(EntityType_Kind_name, int32(x))
}
func (EntityType_Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Represents different entity type expansion modes. Automated expansion
// allows an agent to recognize values that have not been explicitly listed in
// the entity (for example, new kinds of shopping list items).
type EntityType_AutoExpansionMode int32

const (
	// Auto expansion disabled for the entity.
	EntityType_AUTO_EXPANSION_MODE_UNSPECIFIED EntityType_AutoExpansionMode = 0
	// Allows an agent to recognize values that have not been explicitly
	// listed in the entity.
	EntityType_AUTO_EXPANSION_MODE_DEFAULT EntityType_AutoExpansionMode = 1
)

var EntityType_AutoExpansionMode_name = map[int32]string{
	0: "AUTO_EXPANSION_MODE_UNSPECIFIED",
	1: "AUTO_EXPANSION_MODE_DEFAULT",
}
var EntityType_AutoExpansionMode_value = map[string]int32{
	"AUTO_EXPANSION_MODE_UNSPECIFIED": 0,
	"AUTO_EXPANSION_MODE_DEFAULT":     1,
}

func (x EntityType_AutoExpansionMode) String() string {
	return proto.EnumName(EntityType_AutoExpansionMode_name, int32(x))
}
func (EntityType_AutoExpansionMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 1}
}

// Represents an entity type.
// Entity types serve as a tool for extracting parameter values from natural
// language queries.
type EntityType struct {
	// Required. The unique identifier of the entity type. Format:
	// `projects/<Project ID>/agent/entityTypes/<Entity Type ID>`.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Required. The name of the entity.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	// Required. Indicates the kind of entity type.
	Kind EntityType_Kind `protobuf:"varint,3,opt,name=kind,enum=google.cloud.dialogflow.v2beta1.EntityType_Kind" json:"kind,omitempty"`
	// Optional. Indicates whether the entity type can be automatically
	// expanded.
	AutoExpansionMode EntityType_AutoExpansionMode `protobuf:"varint,4,opt,name=auto_expansion_mode,json=autoExpansionMode,enum=google.cloud.dialogflow.v2beta1.EntityType_AutoExpansionMode" json:"auto_expansion_mode,omitempty"`
	// Optional. The collection of entities associated with the entity type.
	Entities []*EntityType_Entity `protobuf:"bytes,6,rep,name=entities" json:"entities,omitempty"`
}

func (m *EntityType) Reset()                    { *m = EntityType{} }
func (m *EntityType) String() string            { return proto.CompactTextString(m) }
func (*EntityType) ProtoMessage()               {}
func (*EntityType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EntityType) GetEntities() []*EntityType_Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

// Optional. Represents an entity.
type EntityType_Entity struct {
	// Required.
	// For `KIND_MAP` entity types:
	//   A canonical name to be used in place of synonyms.
	// For `KIND_LIST` entity types:
	//   A string that can contain references to other entity types (with or
	//   without aliases).
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	// Required. A collection of synonyms. For `KIND_LIST` entity types this
	// must contain exactly one synonym equal to `value`.
	Synonyms []string `protobuf:"bytes,2,rep,name=synonyms" json:"synonyms,omitempty"`
}

func (m *EntityType_Entity) Reset()                    { *m = EntityType_Entity{} }
func (m *EntityType_Entity) String() string            { return proto.CompactTextString(m) }
func (*EntityType_Entity) ProtoMessage()               {}
func (*EntityType_Entity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// The request message for [EntityTypes.ListEntityTypes].
type ListEntityTypesRequest struct {
	// Required. The agent to list all entity types from.
	// Format: `projects/<Project ID>/agent`.
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// Optional. The language to list entity synonyms for. If not specified,
	// the agent's default language is used.
	// [More than a dozen
	// languages](https://dialogflow.com/docs/reference/language) are supported.
	// Note: languages must be enabled in the agent, before they can be used.
	LanguageCode string `protobuf:"bytes,2,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
	// Optional. The maximum number of items to return in a single page. By
	// default 100 and at most 1000.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	// Optional. The next_page_token value returned from a previous list request.
	PageToken string `protobuf:"bytes,4,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
}

func (m *ListEntityTypesRequest) Reset()                    { *m = ListEntityTypesRequest{} }
func (m *ListEntityTypesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListEntityTypesRequest) ProtoMessage()               {}
func (*ListEntityTypesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// The response message for [EntityTypes.ListEntityTypes].
type ListEntityTypesResponse struct {
	// The list of agent entity types. There will be a maximum number of items
	// returned based on the page_size field in the request.
	EntityTypes []*EntityType `protobuf:"bytes,1,rep,name=entity_types,json=entityTypes" json:"entity_types,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no
	// more results in the list.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
}

func (m *ListEntityTypesResponse) Reset()                    { *m = ListEntityTypesResponse{} }
func (m *ListEntityTypesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListEntityTypesResponse) ProtoMessage()               {}
func (*ListEntityTypesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListEntityTypesResponse) GetEntityTypes() []*EntityType {
	if m != nil {
		return m.EntityTypes
	}
	return nil
}

// The request message for [EntityTypes.GetEntityType].
type GetEntityTypeRequest struct {
	// Required. The name of the entity type.
	// Format: `projects/<Project ID>/agent/entityTypes/<EntityType ID>`.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Optional. The language to retrieve entity synonyms for. If not specified,
	// the agent's default language is used.
	// [More than a dozen
	// languages](https://dialogflow.com/docs/reference/language) are supported.
	// Note: languages must be enabled in the agent, before they can be used.
	LanguageCode string `protobuf:"bytes,2,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
}

func (m *GetEntityTypeRequest) Reset()                    { *m = GetEntityTypeRequest{} }
func (m *GetEntityTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEntityTypeRequest) ProtoMessage()               {}
func (*GetEntityTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// The request message for [EntityTypes.CreateEntityType].
type CreateEntityTypeRequest struct {
	// Required. The agent to create a entity type for.
	// Format: `projects/<Project ID>/agent`.
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// Required. The entity type to create.
	EntityType *EntityType `protobuf:"bytes,2,opt,name=entity_type,json=entityType" json:"entity_type,omitempty"`
	// Optional. The language of entity synonyms defined in `entity_type`. If not
	// specified, the agent's default language is used.
	// [More than a dozen
	// languages](https://dialogflow.com/docs/reference/language) are supported.
	// Note: languages must be enabled in the agent, before they can be used.
	LanguageCode string `protobuf:"bytes,3,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
}

func (m *CreateEntityTypeRequest) Reset()                    { *m = CreateEntityTypeRequest{} }
func (m *CreateEntityTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateEntityTypeRequest) ProtoMessage()               {}
func (*CreateEntityTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateEntityTypeRequest) GetEntityType() *EntityType {
	if m != nil {
		return m.EntityType
	}
	return nil
}

// The request message for [EntityTypes.UpdateEntityType].
type UpdateEntityTypeRequest struct {
	// Required. The entity type to update.
	// Format: `projects/<Project ID>/agent/entityTypes/<EntityType ID>`.
	EntityType *EntityType `protobuf:"bytes,1,opt,name=entity_type,json=entityType" json:"entity_type,omitempty"`
	// Optional. The language of entity synonyms defined in `entity_type`. If not
	// specified, the agent's default language is used.
	// [More than a dozen
	// languages](https://dialogflow.com/docs/reference/language) are supported.
	// Note: languages must be enabled in the agent, before they can be used.
	LanguageCode string `protobuf:"bytes,2,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
	// Optional. The mask to control which fields get updated.
	UpdateMask *google_protobuf3.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
}

func (m *UpdateEntityTypeRequest) Reset()                    { *m = UpdateEntityTypeRequest{} }
func (m *UpdateEntityTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateEntityTypeRequest) ProtoMessage()               {}
func (*UpdateEntityTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateEntityTypeRequest) GetEntityType() *EntityType {
	if m != nil {
		return m.EntityType
	}
	return nil
}

func (m *UpdateEntityTypeRequest) GetUpdateMask() *google_protobuf3.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

// The request message for [EntityTypes.DeleteEntityType].
type DeleteEntityTypeRequest struct {
	// Required. The name of the entity type to delete.
	// Format: `projects/<Project ID>/agent/entityTypes/<EntityType ID>`.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteEntityTypeRequest) Reset()                    { *m = DeleteEntityTypeRequest{} }
func (m *DeleteEntityTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteEntityTypeRequest) ProtoMessage()               {}
func (*DeleteEntityTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// The request message for [EntityTypes.BatchUpdateEntityTypes].
type BatchUpdateEntityTypesRequest struct {
	// Required. The name of the agent to update or create entity types in.
	// Format: `projects/<Project ID>/agent`.
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// Required. The source of the entity type batch.
	//
	// For each entity type in the batch:
	// * If `name` is specified, we update an existing entity type.
	// * If `name` is not specified, we create a new entity type.
	//
	// Types that are valid to be assigned to EntityTypeBatch:
	//	*BatchUpdateEntityTypesRequest_EntityTypeBatchUri
	//	*BatchUpdateEntityTypesRequest_EntityTypeBatchInline
	EntityTypeBatch isBatchUpdateEntityTypesRequest_EntityTypeBatch `protobuf_oneof:"entity_type_batch"`
	// Optional. The language of entity synonyms defined in `entity_types`. If not
	// specified, the agent's default language is used.
	// [More than a dozen
	// languages](https://dialogflow.com/docs/reference/language) are supported.
	// Note: languages must be enabled in the agent, before they can be used.
	LanguageCode string `protobuf:"bytes,4,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
	// Optional. The mask to control which fields get updated.
	UpdateMask *google_protobuf3.FieldMask `protobuf:"bytes,5,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
}

func (m *BatchUpdateEntityTypesRequest) Reset()                    { *m = BatchUpdateEntityTypesRequest{} }
func (m *BatchUpdateEntityTypesRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchUpdateEntityTypesRequest) ProtoMessage()               {}
func (*BatchUpdateEntityTypesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type isBatchUpdateEntityTypesRequest_EntityTypeBatch interface {
	isBatchUpdateEntityTypesRequest_EntityTypeBatch()
}

type BatchUpdateEntityTypesRequest_EntityTypeBatchUri struct {
	EntityTypeBatchUri string `protobuf:"bytes,2,opt,name=entity_type_batch_uri,json=entityTypeBatchUri,oneof"`
}
type BatchUpdateEntityTypesRequest_EntityTypeBatchInline struct {
	EntityTypeBatchInline *EntityTypeBatch `protobuf:"bytes,3,opt,name=entity_type_batch_inline,json=entityTypeBatchInline,oneof"`
}

func (*BatchUpdateEntityTypesRequest_EntityTypeBatchUri) isBatchUpdateEntityTypesRequest_EntityTypeBatch() {
}
func (*BatchUpdateEntityTypesRequest_EntityTypeBatchInline) isBatchUpdateEntityTypesRequest_EntityTypeBatch() {
}

func (m *BatchUpdateEntityTypesRequest) GetEntityTypeBatch() isBatchUpdateEntityTypesRequest_EntityTypeBatch {
	if m != nil {
		return m.EntityTypeBatch
	}
	return nil
}

func (m *BatchUpdateEntityTypesRequest) GetEntityTypeBatchUri() string {
	if x, ok := m.GetEntityTypeBatch().(*BatchUpdateEntityTypesRequest_EntityTypeBatchUri); ok {
		return x.EntityTypeBatchUri
	}
	return ""
}

func (m *BatchUpdateEntityTypesRequest) GetEntityTypeBatchInline() *EntityTypeBatch {
	if x, ok := m.GetEntityTypeBatch().(*BatchUpdateEntityTypesRequest_EntityTypeBatchInline); ok {
		return x.EntityTypeBatchInline
	}
	return nil
}

func (m *BatchUpdateEntityTypesRequest) GetUpdateMask() *google_protobuf3.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BatchUpdateEntityTypesRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _BatchUpdateEntityTypesRequest_OneofMarshaler, _BatchUpdateEntityTypesRequest_OneofUnmarshaler, _BatchUpdateEntityTypesRequest_OneofSizer, []interface{}{
		(*BatchUpdateEntityTypesRequest_EntityTypeBatchUri)(nil),
		(*BatchUpdateEntityTypesRequest_EntityTypeBatchInline)(nil),
	}
}

func _BatchUpdateEntityTypesRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BatchUpdateEntityTypesRequest)
	// entity_type_batch
	switch x := m.EntityTypeBatch.(type) {
	case *BatchUpdateEntityTypesRequest_EntityTypeBatchUri:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.EntityTypeBatchUri)
	case *BatchUpdateEntityTypesRequest_EntityTypeBatchInline:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EntityTypeBatchInline); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("BatchUpdateEntityTypesRequest.EntityTypeBatch has unexpected type %T", x)
	}
	return nil
}

func _BatchUpdateEntityTypesRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BatchUpdateEntityTypesRequest)
	switch tag {
	case 2: // entity_type_batch.entity_type_batch_uri
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.EntityTypeBatch = &BatchUpdateEntityTypesRequest_EntityTypeBatchUri{x}
		return true, err
	case 3: // entity_type_batch.entity_type_batch_inline
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EntityTypeBatch)
		err := b.DecodeMessage(msg)
		m.EntityTypeBatch = &BatchUpdateEntityTypesRequest_EntityTypeBatchInline{msg}
		return true, err
	default:
		return false, nil
	}
}

func _BatchUpdateEntityTypesRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*BatchUpdateEntityTypesRequest)
	// entity_type_batch
	switch x := m.EntityTypeBatch.(type) {
	case *BatchUpdateEntityTypesRequest_EntityTypeBatchUri:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.EntityTypeBatchUri)))
		n += len(x.EntityTypeBatchUri)
	case *BatchUpdateEntityTypesRequest_EntityTypeBatchInline:
		s := proto.Size(x.EntityTypeBatchInline)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// The response message for [EntityTypes.BatchUpdateEntityTypes].
type BatchUpdateEntityTypesResponse struct {
	// The collection of updated or created entity types.
	EntityTypes []*EntityType `protobuf:"bytes,1,rep,name=entity_types,json=entityTypes" json:"entity_types,omitempty"`
}

func (m *BatchUpdateEntityTypesResponse) Reset()                    { *m = BatchUpdateEntityTypesResponse{} }
func (m *BatchUpdateEntityTypesResponse) String() string            { return proto.CompactTextString(m) }
func (*BatchUpdateEntityTypesResponse) ProtoMessage()               {}
func (*BatchUpdateEntityTypesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BatchUpdateEntityTypesResponse) GetEntityTypes() []*EntityType {
	if m != nil {
		return m.EntityTypes
	}
	return nil
}

// The request message for [EntityTypes.BatchDeleteEntityTypes].
type BatchDeleteEntityTypesRequest struct {
	// Required. The name of the agent to delete all entities types for. Format:
	// `projects/<Project ID>/agent`.
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// Required. The names entity types to delete. All names must point to the
	// same agent as `parent`.
	EntityTypeNames []string `protobuf:"bytes,2,rep,name=entity_type_names,json=entityTypeNames" json:"entity_type_names,omitempty"`
}

func (m *BatchDeleteEntityTypesRequest) Reset()                    { *m = BatchDeleteEntityTypesRequest{} }
func (m *BatchDeleteEntityTypesRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchDeleteEntityTypesRequest) ProtoMessage()               {}
func (*BatchDeleteEntityTypesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// The request message for [EntityTypes.BatchCreateEntities].
type BatchCreateEntitiesRequest struct {
	// Required. The name of the entity type to create entities in. Format:
	// `projects/<Project ID>/agent/entityTypes/<Entity Type ID>`.
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// Required. The collection of entities to create.
	Entities []*EntityType_Entity `protobuf:"bytes,2,rep,name=entities" json:"entities,omitempty"`
	// Optional. The language of entity synonyms defined in `entities`. If not
	// specified, the agent's default language is used.
	// [More than a dozen
	// languages](https://dialogflow.com/docs/reference/language) are supported.
	// Note: languages must be enabled in the agent, before they can be used.
	LanguageCode string `protobuf:"bytes,3,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
}

func (m *BatchCreateEntitiesRequest) Reset()                    { *m = BatchCreateEntitiesRequest{} }
func (m *BatchCreateEntitiesRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchCreateEntitiesRequest) ProtoMessage()               {}
func (*BatchCreateEntitiesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *BatchCreateEntitiesRequest) GetEntities() []*EntityType_Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

// The response message for [EntityTypes.BatchCreateEntities].
type BatchUpdateEntitiesRequest struct {
	// Required. The name of the entity type to update the entities in. Format:
	// `projects/<Project ID>/agent/entityTypes/<Entity Type ID>`.
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// Required. The collection of new entities to replace the existing entities.
	Entities []*EntityType_Entity `protobuf:"bytes,2,rep,name=entities" json:"entities,omitempty"`
	// Optional. The language of entity synonyms defined in `entities`. If not
	// specified, the agent's default language is used.
	// [More than a dozen
	// languages](https://dialogflow.com/docs/reference/language) are supported.
	// Note: languages must be enabled in the agent, before they can be used.
	LanguageCode string `protobuf:"bytes,3,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
	// Optional. The mask to control which fields get updated.
	UpdateMask *google_protobuf3.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
}

func (m *BatchUpdateEntitiesRequest) Reset()                    { *m = BatchUpdateEntitiesRequest{} }
func (m *BatchUpdateEntitiesRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchUpdateEntitiesRequest) ProtoMessage()               {}
func (*BatchUpdateEntitiesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *BatchUpdateEntitiesRequest) GetEntities() []*EntityType_Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *BatchUpdateEntitiesRequest) GetUpdateMask() *google_protobuf3.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

// The request message for [EntityTypes.BatchDeleteEntities].
type BatchDeleteEntitiesRequest struct {
	// Required. The name of the entity type to delete entries for. Format:
	// `projects/<Project ID>/agent/entityTypes/<Entity Type ID>`.
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// Required. The canonical `values` of the entities to delete. Note that
	// these are not fully-qualified names, i.e. they don't start with
	// `projects/<Project ID>`.
	EntityValues []string `protobuf:"bytes,2,rep,name=entity_values,json=entityValues" json:"entity_values,omitempty"`
	// Optional. The language of entity synonyms defined in `entities`. If not
	// specified, the agent's default language is used.
	// [More than a dozen
	// languages](https://dialogflow.com/docs/reference/language) are supported.
	// Note: languages must be enabled in the agent, before they can be used.
	LanguageCode string `protobuf:"bytes,3,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
}

func (m *BatchDeleteEntitiesRequest) Reset()                    { *m = BatchDeleteEntitiesRequest{} }
func (m *BatchDeleteEntitiesRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchDeleteEntitiesRequest) ProtoMessage()               {}
func (*BatchDeleteEntitiesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

// This message is a wrapper around a collection of entity types.
type EntityTypeBatch struct {
	// A collection of entity types.
	EntityTypes []*EntityType `protobuf:"bytes,1,rep,name=entity_types,json=entityTypes" json:"entity_types,omitempty"`
}

func (m *EntityTypeBatch) Reset()                    { *m = EntityTypeBatch{} }
func (m *EntityTypeBatch) String() string            { return proto.CompactTextString(m) }
func (*EntityTypeBatch) ProtoMessage()               {}
func (*EntityTypeBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *EntityTypeBatch) GetEntityTypes() []*EntityType {
	if m != nil {
		return m.EntityTypes
	}
	return nil
}

func init() {
	proto.RegisterType((*EntityType)(nil), "google.cloud.dialogflow.v2beta1.EntityType")
	proto.RegisterType((*EntityType_Entity)(nil), "google.cloud.dialogflow.v2beta1.EntityType.Entity")
	proto.RegisterType((*ListEntityTypesRequest)(nil), "google.cloud.dialogflow.v2beta1.ListEntityTypesRequest")
	proto.RegisterType((*ListEntityTypesResponse)(nil), "google.cloud.dialogflow.v2beta1.ListEntityTypesResponse")
	proto.RegisterType((*GetEntityTypeRequest)(nil), "google.cloud.dialogflow.v2beta1.GetEntityTypeRequest")
	proto.RegisterType((*CreateEntityTypeRequest)(nil), "google.cloud.dialogflow.v2beta1.CreateEntityTypeRequest")
	proto.RegisterType((*UpdateEntityTypeRequest)(nil), "google.cloud.dialogflow.v2beta1.UpdateEntityTypeRequest")
	proto.RegisterType((*DeleteEntityTypeRequest)(nil), "google.cloud.dialogflow.v2beta1.DeleteEntityTypeRequest")
	proto.RegisterType((*BatchUpdateEntityTypesRequest)(nil), "google.cloud.dialogflow.v2beta1.BatchUpdateEntityTypesRequest")
	proto.RegisterType((*BatchUpdateEntityTypesResponse)(nil), "google.cloud.dialogflow.v2beta1.BatchUpdateEntityTypesResponse")
	proto.RegisterType((*BatchDeleteEntityTypesRequest)(nil), "google.cloud.dialogflow.v2beta1.BatchDeleteEntityTypesRequest")
	proto.RegisterType((*BatchCreateEntitiesRequest)(nil), "google.cloud.dialogflow.v2beta1.BatchCreateEntitiesRequest")
	proto.RegisterType((*BatchUpdateEntitiesRequest)(nil), "google.cloud.dialogflow.v2beta1.BatchUpdateEntitiesRequest")
	proto.RegisterType((*BatchDeleteEntitiesRequest)(nil), "google.cloud.dialogflow.v2beta1.BatchDeleteEntitiesRequest")
	proto.RegisterType((*EntityTypeBatch)(nil), "google.cloud.dialogflow.v2beta1.EntityTypeBatch")
	proto.RegisterEnum("google.cloud.dialogflow.v2beta1.EntityType_Kind", EntityType_Kind_name, EntityType_Kind_value)
	proto.RegisterEnum("google.cloud.dialogflow.v2beta1.EntityType_AutoExpansionMode", EntityType_AutoExpansionMode_name, EntityType_AutoExpansionMode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EntityTypes service

type EntityTypesClient interface {
	// Returns the list of all entity types in the specified agent.
	ListEntityTypes(ctx context.Context, in *ListEntityTypesRequest, opts ...grpc.CallOption) (*ListEntityTypesResponse, error)
	// Retrieves the specified entity type.
	GetEntityType(ctx context.Context, in *GetEntityTypeRequest, opts ...grpc.CallOption) (*EntityType, error)
	// Creates an entity type in the specified agent.
	CreateEntityType(ctx context.Context, in *CreateEntityTypeRequest, opts ...grpc.CallOption) (*EntityType, error)
	// Updates the specified entity type.
	UpdateEntityType(ctx context.Context, in *UpdateEntityTypeRequest, opts ...grpc.CallOption) (*EntityType, error)
	// Deletes the specified entity type.
	DeleteEntityType(ctx context.Context, in *DeleteEntityTypeRequest, opts ...grpc.CallOption) (*google_protobuf2.Empty, error)
	// Updates/Creates multiple entity types in the specified agent.
	//
	// Operation<response: BatchUpdateEntityTypesResponse,
	//           metadata: google.protobuf.Struct>
	BatchUpdateEntityTypes(ctx context.Context, in *BatchUpdateEntityTypesRequest, opts ...grpc.CallOption) (*google_longrunning.Operation, error)
	// Deletes entity types in the specified agent.
	//
	// Operation<response: google.protobuf.Empty,
	//           metadata: google.protobuf.Struct>
	BatchDeleteEntityTypes(ctx context.Context, in *BatchDeleteEntityTypesRequest, opts ...grpc.CallOption) (*google_longrunning.Operation, error)
	// Creates multiple new entities in the specified entity type (extends the
	// existing collection of entries).
	//
	// Operation<response: google.protobuf.Empty>
	BatchCreateEntities(ctx context.Context, in *BatchCreateEntitiesRequest, opts ...grpc.CallOption) (*google_longrunning.Operation, error)
	// Updates entities in the specified entity type (replaces the existing
	// collection of entries).
	//
	// Operation<response: google.protobuf.Empty,
	//           metadata: google.protobuf.Struct>
	BatchUpdateEntities(ctx context.Context, in *BatchUpdateEntitiesRequest, opts ...grpc.CallOption) (*google_longrunning.Operation, error)
	// Deletes entities in the specified entity type.
	//
	// Operation<response: google.protobuf.Empty,
	//           metadata: google.protobuf.Struct>
	BatchDeleteEntities(ctx context.Context, in *BatchDeleteEntitiesRequest, opts ...grpc.CallOption) (*google_longrunning.Operation, error)
}

type entityTypesClient struct {
	cc *grpc.ClientConn
}

func NewEntityTypesClient(cc *grpc.ClientConn) EntityTypesClient {
	return &entityTypesClient{cc}
}

func (c *entityTypesClient) ListEntityTypes(ctx context.Context, in *ListEntityTypesRequest, opts ...grpc.CallOption) (*ListEntityTypesResponse, error) {
	out := new(ListEntityTypesResponse)
	err := grpc.Invoke(ctx, "/google.cloud.dialogflow.v2beta1.EntityTypes/ListEntityTypes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityTypesClient) GetEntityType(ctx context.Context, in *GetEntityTypeRequest, opts ...grpc.CallOption) (*EntityType, error) {
	out := new(EntityType)
	err := grpc.Invoke(ctx, "/google.cloud.dialogflow.v2beta1.EntityTypes/GetEntityType", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityTypesClient) CreateEntityType(ctx context.Context, in *CreateEntityTypeRequest, opts ...grpc.CallOption) (*EntityType, error) {
	out := new(EntityType)
	err := grpc.Invoke(ctx, "/google.cloud.dialogflow.v2beta1.EntityTypes/CreateEntityType", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityTypesClient) UpdateEntityType(ctx context.Context, in *UpdateEntityTypeRequest, opts ...grpc.CallOption) (*EntityType, error) {
	out := new(EntityType)
	err := grpc.Invoke(ctx, "/google.cloud.dialogflow.v2beta1.EntityTypes/UpdateEntityType", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityTypesClient) DeleteEntityType(ctx context.Context, in *DeleteEntityTypeRequest, opts ...grpc.CallOption) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	err := grpc.Invoke(ctx, "/google.cloud.dialogflow.v2beta1.EntityTypes/DeleteEntityType", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityTypesClient) BatchUpdateEntityTypes(ctx context.Context, in *BatchUpdateEntityTypesRequest, opts ...grpc.CallOption) (*google_longrunning.Operation, error) {
	out := new(google_longrunning.Operation)
	err := grpc.Invoke(ctx, "/google.cloud.dialogflow.v2beta1.EntityTypes/BatchUpdateEntityTypes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityTypesClient) BatchDeleteEntityTypes(ctx context.Context, in *BatchDeleteEntityTypesRequest, opts ...grpc.CallOption) (*google_longrunning.Operation, error) {
	out := new(google_longrunning.Operation)
	err := grpc.Invoke(ctx, "/google.cloud.dialogflow.v2beta1.EntityTypes/BatchDeleteEntityTypes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityTypesClient) BatchCreateEntities(ctx context.Context, in *BatchCreateEntitiesRequest, opts ...grpc.CallOption) (*google_longrunning.Operation, error) {
	out := new(google_longrunning.Operation)
	err := grpc.Invoke(ctx, "/google.cloud.dialogflow.v2beta1.EntityTypes/BatchCreateEntities", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityTypesClient) BatchUpdateEntities(ctx context.Context, in *BatchUpdateEntitiesRequest, opts ...grpc.CallOption) (*google_longrunning.Operation, error) {
	out := new(google_longrunning.Operation)
	err := grpc.Invoke(ctx, "/google.cloud.dialogflow.v2beta1.EntityTypes/BatchUpdateEntities", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityTypesClient) BatchDeleteEntities(ctx context.Context, in *BatchDeleteEntitiesRequest, opts ...grpc.CallOption) (*google_longrunning.Operation, error) {
	out := new(google_longrunning.Operation)
	err := grpc.Invoke(ctx, "/google.cloud.dialogflow.v2beta1.EntityTypes/BatchDeleteEntities", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EntityTypes service

type EntityTypesServer interface {
	// Returns the list of all entity types in the specified agent.
	ListEntityTypes(context.Context, *ListEntityTypesRequest) (*ListEntityTypesResponse, error)
	// Retrieves the specified entity type.
	GetEntityType(context.Context, *GetEntityTypeRequest) (*EntityType, error)
	// Creates an entity type in the specified agent.
	CreateEntityType(context.Context, *CreateEntityTypeRequest) (*EntityType, error)
	// Updates the specified entity type.
	UpdateEntityType(context.Context, *UpdateEntityTypeRequest) (*EntityType, error)
	// Deletes the specified entity type.
	DeleteEntityType(context.Context, *DeleteEntityTypeRequest) (*google_protobuf2.Empty, error)
	// Updates/Creates multiple entity types in the specified agent.
	//
	// Operation<response: BatchUpdateEntityTypesResponse,
	//           metadata: google.protobuf.Struct>
	BatchUpdateEntityTypes(context.Context, *BatchUpdateEntityTypesRequest) (*google_longrunning.Operation, error)
	// Deletes entity types in the specified agent.
	//
	// Operation<response: google.protobuf.Empty,
	//           metadata: google.protobuf.Struct>
	BatchDeleteEntityTypes(context.Context, *BatchDeleteEntityTypesRequest) (*google_longrunning.Operation, error)
	// Creates multiple new entities in the specified entity type (extends the
	// existing collection of entries).
	//
	// Operation<response: google.protobuf.Empty>
	BatchCreateEntities(context.Context, *BatchCreateEntitiesRequest) (*google_longrunning.Operation, error)
	// Updates entities in the specified entity type (replaces the existing
	// collection of entries).
	//
	// Operation<response: google.protobuf.Empty,
	//           metadata: google.protobuf.Struct>
	BatchUpdateEntities(context.Context, *BatchUpdateEntitiesRequest) (*google_longrunning.Operation, error)
	// Deletes entities in the specified entity type.
	//
	// Operation<response: google.protobuf.Empty,
	//           metadata: google.protobuf.Struct>
	BatchDeleteEntities(context.Context, *BatchDeleteEntitiesRequest) (*google_longrunning.Operation, error)
}

func RegisterEntityTypesServer(s *grpc.Server, srv EntityTypesServer) {
	s.RegisterService(&_EntityTypes_serviceDesc, srv)
}

func _EntityTypes_ListEntityTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntityTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityTypesServer).ListEntityTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.dialogflow.v2beta1.EntityTypes/ListEntityTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityTypesServer).ListEntityTypes(ctx, req.(*ListEntityTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityTypes_GetEntityType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityTypesServer).GetEntityType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.dialogflow.v2beta1.EntityTypes/GetEntityType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityTypesServer).GetEntityType(ctx, req.(*GetEntityTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityTypes_CreateEntityType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntityTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityTypesServer).CreateEntityType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.dialogflow.v2beta1.EntityTypes/CreateEntityType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityTypesServer).CreateEntityType(ctx, req.(*CreateEntityTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityTypes_UpdateEntityType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEntityTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityTypesServer).UpdateEntityType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.dialogflow.v2beta1.EntityTypes/UpdateEntityType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityTypesServer).UpdateEntityType(ctx, req.(*UpdateEntityTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityTypes_DeleteEntityType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEntityTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityTypesServer).DeleteEntityType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.dialogflow.v2beta1.EntityTypes/DeleteEntityType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityTypesServer).DeleteEntityType(ctx, req.(*DeleteEntityTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityTypes_BatchUpdateEntityTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateEntityTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityTypesServer).BatchUpdateEntityTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.dialogflow.v2beta1.EntityTypes/BatchUpdateEntityTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityTypesServer).BatchUpdateEntityTypes(ctx, req.(*BatchUpdateEntityTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityTypes_BatchDeleteEntityTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteEntityTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityTypesServer).BatchDeleteEntityTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.dialogflow.v2beta1.EntityTypes/BatchDeleteEntityTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityTypesServer).BatchDeleteEntityTypes(ctx, req.(*BatchDeleteEntityTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityTypes_BatchCreateEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityTypesServer).BatchCreateEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.dialogflow.v2beta1.EntityTypes/BatchCreateEntities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityTypesServer).BatchCreateEntities(ctx, req.(*BatchCreateEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityTypes_BatchUpdateEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityTypesServer).BatchUpdateEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.dialogflow.v2beta1.EntityTypes/BatchUpdateEntities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityTypesServer).BatchUpdateEntities(ctx, req.(*BatchUpdateEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityTypes_BatchDeleteEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityTypesServer).BatchDeleteEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.dialogflow.v2beta1.EntityTypes/BatchDeleteEntities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityTypesServer).BatchDeleteEntities(ctx, req.(*BatchDeleteEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EntityTypes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.cloud.dialogflow.v2beta1.EntityTypes",
	HandlerType: (*EntityTypesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEntityTypes",
			Handler:    _EntityTypes_ListEntityTypes_Handler,
		},
		{
			MethodName: "GetEntityType",
			Handler:    _EntityTypes_GetEntityType_Handler,
		},
		{
			MethodName: "CreateEntityType",
			Handler:    _EntityTypes_CreateEntityType_Handler,
		},
		{
			MethodName: "UpdateEntityType",
			Handler:    _EntityTypes_UpdateEntityType_Handler,
		},
		{
			MethodName: "DeleteEntityType",
			Handler:    _EntityTypes_DeleteEntityType_Handler,
		},
		{
			MethodName: "BatchUpdateEntityTypes",
			Handler:    _EntityTypes_BatchUpdateEntityTypes_Handler,
		},
		{
			MethodName: "BatchDeleteEntityTypes",
			Handler:    _EntityTypes_BatchDeleteEntityTypes_Handler,
		},
		{
			MethodName: "BatchCreateEntities",
			Handler:    _EntityTypes_BatchCreateEntities_Handler,
		},
		{
			MethodName: "BatchUpdateEntities",
			Handler:    _EntityTypes_BatchUpdateEntities_Handler,
		},
		{
			MethodName: "BatchDeleteEntities",
			Handler:    _EntityTypes_BatchDeleteEntities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/cloud/dialogflow/v2beta1/entity_type.proto",
}

func init() { proto.RegisterFile("google/cloud/dialogflow/v2beta1/entity_type.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xdf, 0x6f, 0xdb, 0xd4,
	0x17, 0x9f, 0xd3, 0xac, 0x6a, 0x4f, 0xda, 0x35, 0xbb, 0xdb, 0xda, 0x28, 0xdb, 0xbe, 0xed, 0xd7,
	0x95, 0x50, 0x55, 0x34, 0x7b, 0xcb, 0xc4, 0xaf, 0x4e, 0x03, 0xb5, 0x4d, 0xba, 0x85, 0xf5, 0x47,
	0xe4, 0xb6, 0x13, 0xf0, 0x62, 0x39, 0xc9, 0x9d, 0x77, 0xa9, 0x73, 0xaf, 0x89, 0xaf, 0xc7, 0x32,
	0x34, 0x1e, 0xf8, 0x0f, 0x10, 0x6f, 0x88, 0x27, 0xc4, 0x0b, 0xf0, 0x2f, 0x20, 0x5e, 0x78, 0x82,
	0x27, 0x24, 0x5e, 0x79, 0x44, 0xfc, 0x0d, 0x48, 0xbc, 0x20, 0x5f, 0xdb, 0xb5, 0xe3, 0x38, 0x38,
	0x86, 0x6d, 0xe2, 0x2d, 0xf7, 0xd7, 0x39, 0x9f, 0xcf, 0x39, 0xe7, 0x9e, 0xcf, 0x75, 0xe0, 0x86,
	0xc9, 0x98, 0x69, 0x61, 0xb5, 0x63, 0x31, 0xb7, 0xab, 0x76, 0x89, 0x61, 0x31, 0xf3, 0x81, 0xc5,
	0x3e, 0x54, 0x1f, 0xd5, 0xda, 0x98, 0x1b, 0x37, 0x54, 0x4c, 0x39, 0xe1, 0x03, 0x9d, 0x0f, 0x6c,
	0xac, 0xd8, 0x7d, 0xc6, 0x19, 0x5a, 0xf6, 0x8f, 0x28, 0xe2, 0x88, 0x12, 0x1d, 0x51, 0x82, 0x23,
	0xd5, 0x2b, 0x81, 0x4d, 0xc3, 0x26, 0xaa, 0x41, 0x29, 0xe3, 0x06, 0x27, 0x8c, 0x3a, 0xfe, 0xf1,
	0xea, 0x6a, 0xb0, 0x6a, 0x31, 0x6a, 0xf6, 0x5d, 0x4a, 0x09, 0x35, 0x55, 0x66, 0xe3, 0xfe, 0xd0,
	0xa6, 0xcb, 0xc1, 0x26, 0x31, 0x6a, 0xbb, 0x0f, 0x54, 0xdc, 0xb3, 0xf9, 0x20, 0x58, 0x5c, 0x49,
	0x2e, 0x3e, 0x20, 0xd8, 0xea, 0xea, 0x3d, 0xc3, 0x39, 0x09, 0x76, 0x5c, 0x49, 0xee, 0x70, 0x78,
	0xdf, 0xed, 0x70, 0x7f, 0x55, 0xfe, 0xbc, 0x08, 0xd0, 0x10, 0xb4, 0x8e, 0x06, 0x36, 0x46, 0x08,
	0x8a, 0xd4, 0xe8, 0xe1, 0x8a, 0xb4, 0x22, 0xad, 0xcd, 0x6a, 0xe2, 0x37, 0xfa, 0x3f, 0xcc, 0x75,
	0x89, 0x63, 0x5b, 0xc6, 0x40, 0x17, 0x6b, 0x05, 0xb1, 0x56, 0x0a, 0xe6, 0xf6, 0xbd, 0x2d, 0x75,
	0x28, 0x9e, 0x10, 0xda, 0xad, 0x4c, 0xad, 0x48, 0x6b, 0xe7, 0x6a, 0xd7, 0x95, 0x8c, 0xa8, 0x28,
	0x91, 0x47, 0xe5, 0x1e, 0xa1, 0x5d, 0x4d, 0x9c, 0x46, 0x3d, 0xb8, 0x60, 0xb8, 0x9c, 0xe9, 0xf8,
	0xb1, 0x6d, 0x50, 0x87, 0x30, 0xaa, 0xf7, 0x58, 0x17, 0x57, 0x8a, 0xc2, 0xe8, 0xed, 0x3c, 0x46,
	0x37, 0x5d, 0xce, 0x1a, 0xa1, 0x95, 0x3d, 0xd6, 0xc5, 0xda, 0x79, 0x23, 0x39, 0x85, 0xf6, 0x61,
	0x46, 0x24, 0x94, 0x60, 0xa7, 0x32, 0xbd, 0x32, 0xb5, 0x56, 0xaa, 0xd5, 0xf2, 0xf8, 0xf0, 0x7f,
	0x6a, 0xa7, 0x36, 0xaa, 0x1b, 0x30, 0xed, 0xcf, 0xa1, 0x8b, 0x70, 0xf6, 0x91, 0x61, 0xb9, 0x61,
	0x18, 0xfd, 0x01, 0xaa, 0xc2, 0x8c, 0x33, 0xa0, 0x8c, 0x0e, 0x7a, 0x4e, 0xa5, 0xb0, 0x32, 0xb5,
	0x36, 0xab, 0x9d, 0x8e, 0xe5, 0x37, 0xa0, 0xe8, 0x05, 0x02, 0x5d, 0x84, 0xf2, 0xbd, 0xe6, 0x7e,
	0x5d, 0x3f, 0xde, 0x3f, 0x6c, 0x35, 0xb6, 0x9b, 0x3b, 0xcd, 0x46, 0xbd, 0x7c, 0x06, 0xcd, 0xc1,
	0x8c, 0x98, 0xdd, 0xdb, 0x6c, 0x95, 0x25, 0x34, 0x0f, 0xb3, 0x62, 0xb4, 0xdb, 0x3c, 0x3c, 0x2a,
	0x17, 0xe4, 0x77, 0xe1, 0xfc, 0x08, 0x5d, 0xb4, 0x0a, 0xcb, 0x9b, 0xc7, 0x47, 0x07, 0x7a, 0xe3,
	0x9d, 0xd6, 0xe6, 0xfe, 0x61, 0xf3, 0x60, 0x5f, 0xdf, 0x3b, 0xa8, 0x37, 0x12, 0x66, 0x97, 0xe1,
	0x72, 0xda, 0xa6, 0x7a, 0x63, 0x67, 0xf3, 0x78, 0xf7, 0xa8, 0x2c, 0xc9, 0x9f, 0x4a, 0xb0, 0xb8,
	0x4b, 0x1c, 0x1e, 0xb1, 0x76, 0x34, 0xfc, 0x81, 0x8b, 0x1d, 0x8e, 0x16, 0x61, 0xda, 0x36, 0xfa,
	0x98, 0xf2, 0x80, 0x63, 0x30, 0x42, 0xab, 0x30, 0x6f, 0x19, 0xd4, 0x74, 0x0d, 0x13, 0xeb, 0x1d,
	0x2f, 0x7b, 0x7e, 0xb5, 0xcc, 0x85, 0x93, 0xdb, 0x1e, 0xba, 0xcb, 0x30, 0x6b, 0x7b, 0x1b, 0x1c,
	0xf2, 0x04, 0x8b, 0x9a, 0x39, 0xab, 0xcd, 0x78, 0x13, 0x87, 0xe4, 0x09, 0x46, 0x57, 0x01, 0xc4,
	0x22, 0x67, 0x27, 0x98, 0x8a, 0xe4, 0xcf, 0x6a, 0x62, 0xfb, 0x91, 0x37, 0xe1, 0x61, 0x5a, 0x1a,
	0xc1, 0xe4, 0xd8, 0x8c, 0x3a, 0x5e, 0x46, 0xe7, 0x62, 0x57, 0xd4, 0xa9, 0x48, 0x22, 0xab, 0x2f,
	0xe7, 0xc8, 0xaa, 0x56, 0xc2, 0x91, 0x5d, 0xf4, 0x12, 0x2c, 0x50, 0xfc, 0x98, 0xeb, 0x31, 0x3c,
	0x3e, 0x9d, 0x79, 0x6f, 0xba, 0x75, 0x8a, 0xe9, 0x00, 0x2e, 0xde, 0xc1, 0x31, 0x44, 0x61, 0x90,
	0xd2, 0x6e, 0xd3, 0x24, 0x01, 0x92, 0xbf, 0x92, 0x60, 0x69, 0xbb, 0x8f, 0x0d, 0x8e, 0x47, 0x8d,
	0x8e, 0x8b, 0xfc, 0x2e, 0x94, 0x62, 0xe4, 0x85, 0xd9, 0x9c, 0xdc, 0x21, 0xe2, 0x3e, 0x0a, 0x73,
	0x2a, 0x05, 0xe6, 0x8f, 0x12, 0x2c, 0x1d, 0xdb, 0xdd, 0x54, 0x98, 0x09, 0x38, 0xd2, 0x33, 0x86,
	0x93, 0x56, 0x56, 0xb7, 0xa0, 0xe4, 0x0a, 0x34, 0xa2, 0xfd, 0x09, 0xc4, 0xa5, 0x5a, 0x35, 0x74,
	0x19, 0xf6, 0x3f, 0x65, 0xc7, 0xeb, 0x90, 0x7b, 0x86, 0x73, 0xa2, 0x81, 0xbf, 0xdd, 0xfb, 0x2d,
	0x5f, 0x83, 0xa5, 0x3a, 0xb6, 0x70, 0x1a, 0x95, 0x94, 0x34, 0xca, 0x3f, 0x17, 0xe0, 0xea, 0x96,
	0xc1, 0x3b, 0x0f, 0x93, 0xfc, 0x33, 0x6f, 0xc8, 0x4d, 0xb8, 0x14, 0x0b, 0x8c, 0xde, 0xf6, 0x8c,
	0xe8, 0x6e, 0x9f, 0xf8, 0x94, 0xee, 0x9e, 0xd1, 0x50, 0xc4, 0xdb, 0xf7, 0xd0, 0x27, 0xe8, 0x04,
	0x2a, 0xa3, 0x87, 0x08, 0xb5, 0x08, 0xc5, 0x01, 0xcf, 0x3c, 0x4d, 0x57, 0x98, 0xbd, 0x7b, 0x46,
	0xbb, 0x94, 0xf0, 0xd4, 0x14, 0x06, 0x47, 0x83, 0x5d, 0xcc, 0x0e, 0xf6, 0xd9, 0x3c, 0xc1, 0xde,
	0xba, 0x00, 0xe7, 0x47, 0xe8, 0xc8, 0x36, 0xfc, 0x6f, 0x5c, 0x44, 0x9f, 0xcf, 0xfd, 0x96, 0x3b,
	0x41, 0x0e, 0x93, 0x89, 0xcf, 0xcc, 0xe1, 0xfa, 0x30, 0x7e, 0xaf, 0x22, 0xc2, 0x9e, 0xbe, 0x10,
	0x39, 0xf0, 0xa4, 0xd1, 0x91, 0xbf, 0x96, 0xa0, 0x2a, 0xbc, 0xc4, 0x2e, 0x34, 0xc9, 0x76, 0x11,
	0x57, 0xa7, 0xc2, 0xbf, 0x57, 0xa7, 0xc9, 0x2e, 0xf4, 0xef, 0x21, 0xd6, 0x58, 0x0e, 0xfe, 0xa3,
	0x58, 0x93, 0x05, 0x58, 0xcc, 0x75, 0xdb, 0x3f, 0x0e, 0x78, 0xc6, 0x32, 0x4f, 0x26, 0x12, 0xb7,
	0x20, 0xed, 0x42, 0xd1, 0xc3, 0x94, 0x07, 0x45, 0x79, 0x5f, 0xcc, 0x4d, 0x16, 0x68, 0x03, 0x16,
	0x12, 0xd7, 0xf1, 0x59, 0x17, 0x77, 0xed, 0xcf, 0x73, 0x50, 0x8a, 0x95, 0x34, 0xfa, 0x4e, 0x82,
	0x85, 0x84, 0x70, 0xa2, 0xd7, 0x32, 0xad, 0xa7, 0xcb, 0x7f, 0xf5, 0xf5, 0xfc, 0x07, 0xfd, 0x3b,
	0x2c, 0xbf, 0xfa, 0xc9, 0x2f, 0xbf, 0x7d, 0x56, 0xb8, 0x8e, 0x94, 0xd3, 0x57, 0xf5, 0x47, 0x7e,
	0x74, 0x6f, 0xdb, 0x7d, 0xf6, 0x3e, 0xee, 0x70, 0x47, 0x5d, 0x57, 0x0d, 0x13, 0x53, 0xfe, 0x54,
	0x8d, 0x6b, 0xf1, 0xb7, 0x12, 0xcc, 0x0f, 0x89, 0x2c, 0x7a, 0x25, 0x13, 0x43, 0x9a, 0x28, 0x57,
	0xf3, 0x44, 0x34, 0x0d, 0xad, 0x77, 0xd9, 0x47, 0xb0, 0xc6, 0xa1, 0xaa, 0xeb, 0x4f, 0xd1, 0xf7,
	0x12, 0x94, 0x93, 0x02, 0x8e, 0xb2, 0x83, 0x36, 0x46, 0xf3, 0xf3, 0x61, 0xde, 0x16, 0x98, 0x6f,
	0xcb, 0x39, 0x23, 0xbc, 0x11, 0xd7, 0x6b, 0xf4, 0x93, 0x04, 0xe5, 0x64, 0x23, 0x9e, 0x80, 0xc0,
	0x98, 0xd7, 0x40, 0x3e, 0x02, 0x07, 0x82, 0x40, 0xb3, 0xb6, 0x11, 0x11, 0x88, 0x7f, 0x79, 0x4d,
	0x92, 0x80, 0x61, 0x32, 0x5f, 0x48, 0x50, 0x4e, 0xf6, 0xf8, 0x09, 0xc8, 0x8c, 0x79, 0x0f, 0x54,
	0x17, 0x47, 0x9a, 0x4c, 0xc3, 0xfb, 0x22, 0x0b, 0x8b, 0x65, 0xfd, 0x1f, 0x14, 0xcb, 0x62, 0xba,
	0xf2, 0xa1, 0x37, 0x33, 0x41, 0xfe, 0xed, 0x23, 0xa4, 0x7a, 0x35, 0x3c, 0x1f, 0xfb, 0xc2, 0x54,
	0x0e, 0xc2, 0x2f, 0x4c, 0xb9, 0x21, 0x10, 0xbf, 0x25, 0x6f, 0xe4, 0x2c, 0x95, 0x76, 0xe4, 0x74,
	0x43, 0x5a, 0x8f, 0x08, 0x8c, 0x08, 0xe9, 0xa4, 0x04, 0xc6, 0x29, 0xf0, 0x73, 0x25, 0xe0, 0x3b,
	0xf5, 0x08, 0xfc, 0x20, 0xc1, 0x85, 0x14, 0x8d, 0x46, 0xb7, 0x26, 0x43, 0x9f, 0xaa, 0xec, 0x59,
	0xd0, 0x5b, 0x02, 0xfa, 0xdb, 0x72, 0x23, 0x13, 0x7a, 0xa2, 0x5e, 0xd4, 0x50, 0x27, 0x7d, 0x16,
	0xbe, 0xf3, 0x21, 0x16, 0xc3, 0xea, 0x3d, 0x29, 0x8b, 0x54, 0xcd, 0x7f, 0x51, 0x2c, 0xa2, 0x62,
	0x3a, 0x65, 0x31, 0xac, 0xcd, 0x93, 0xb2, 0x48, 0x55, 0xf4, 0x17, 0xc5, 0xe2, 0xb4, 0xa2, 0xb6,
	0x7e, 0x95, 0x60, 0xb5, 0xc3, 0x7a, 0x59, 0x98, 0xb7, 0x62, 0xcf, 0x80, 0x96, 0xd7, 0x4d, 0x5a,
	0xd2, 0x7b, 0x8f, 0x4d, 0xc2, 0x1f, 0xba, 0x6d, 0xa5, 0xc3, 0x7a, 0x2a, 0x7f, 0x48, 0xda, 0x86,
	0x6b, 0x71, 0x0b, 0x33, 0xd7, 0x18, 0xc4, 0xfe, 0x93, 0xba, 0x66, 0xb2, 0x6b, 0x1d, 0x8b, 0x78,
	0x88, 0x02, 0x17, 0x26, 0xf3, 0x5e, 0x18, 0x0a, 0xeb, 0x9b, 0xaa, 0x89, 0xa9, 0x68, 0x4d, 0xc1,
	0x92, 0x61, 0x13, 0x67, 0xec, 0x9f, 0x5a, 0xb7, 0xa2, 0xa9, 0x3f, 0x24, 0xe9, 0xcb, 0x42, 0xa1,
	0xbe, 0xf3, 0x4d, 0x61, 0xf9, 0x8e, 0x6f, 0x73, 0x5b, 0xc0, 0xae, 0x47, 0xb0, 0xef, 0xfb, 0x87,
	0xda, 0xd3, 0xc2, 0xfe, 0xcd, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x3d, 0x98, 0x44, 0x33,
	0x13, 0x00, 0x00,
}
