// Code generated by protoc-gen-go.
// source: session.proto
// DO NOT EDIT!

/*
Package dialogflow is a generated protocol buffer package.

It is generated from these files:
	session.proto

It has these top-level messages:
	DetectIntentRequest
	DetectIntentResponse
	QueryParameters
	QueryInput
	QueryResult
	StreamingDetectIntentRequest
	StreamingDetectIntentResponse
	StreamingRecognitionResult
	InputAudioConfig
	TextInput
	EventInput
*/
package dialogflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_cloud_dialogflow_v2beta1 "google.golang.org/genproto/googleapis/cloud/dialogflow/v2beta1"
import google_cloud_dialogflow_v2beta11 "google.golang.org/genproto/googleapis/cloud/dialogflow/v2beta1"
import google_cloud_dialogflow_v2beta13 "google.golang.org/genproto/googleapis/cloud/dialogflow/v2beta1"
import google_protobuf3 "github.com/golang/protobuf/ptypes/struct"
import google_rpc "google.golang.org/genproto/googleapis/rpc/status"
import google_type "google.golang.org/genproto/googleapis/type/latlng"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Audio encoding of the audio content sent in the conversational query request.
// Refer to the [Cloud Speech API documentation](/speech/docs/basics) for more
// details.
type AudioEncoding int32

const (
	// Not specified.
	AudioEncoding_AUDIO_ENCODING_UNSPECIFIED AudioEncoding = 0
	// Uncompressed 16-bit signed little-endian samples (Linear PCM).
	AudioEncoding_AUDIO_ENCODING_LINEAR_16 AudioEncoding = 1
	// [`FLAC`](https://xiph.org/flac/documentation.html) (Free Lossless Audio
	// Codec) is the recommended encoding because it is lossless (therefore
	// recognition is not compromised) and requires only about half the
	// bandwidth of `LINEAR16`. `FLAC` stream encoding supports 16-bit and
	// 24-bit samples, however, not all fields in `STREAMINFO` are supported.
	AudioEncoding_AUDIO_ENCODING_FLAC AudioEncoding = 2
	// 8-bit samples that compand 14-bit audio samples using G.711 PCMU/mu-law.
	AudioEncoding_AUDIO_ENCODING_MULAW AudioEncoding = 3
	// Adaptive Multi-Rate Narrowband codec. `sample_rate_hertz` must be 8000.
	AudioEncoding_AUDIO_ENCODING_AMR AudioEncoding = 4
	// Adaptive Multi-Rate Wideband codec. `sample_rate_hertz` must be 16000.
	AudioEncoding_AUDIO_ENCODING_AMR_WB AudioEncoding = 5
	// Opus encoded audio frames in Ogg container
	// ([OggOpus](https://wiki.xiph.org/OggOpus)).
	// `sample_rate_hertz` must be 16000.
	AudioEncoding_AUDIO_ENCODING_OGG_OPUS AudioEncoding = 6
	// Although the use of lossy encodings is not recommended, if a very low
	// bitrate encoding is required, `OGG_OPUS` is highly preferred over
	// Speex encoding. The [Speex](https://speex.org/) encoding supported by
	// Dialogflow API has a header byte in each block, as in MIME type
	// `audio/x-speex-with-header-byte`.
	// It is a variant of the RTP Speex encoding defined in
	// [RFC 5574](https://tools.ietf.org/html/rfc5574).
	// The stream is a sequence of blocks, one block per RTP packet. Each block
	// starts with a byte containing the length of the block, in bytes, followed
	// by one or more frames of Speex data, padded to an integral number of
	// bytes (octets) as specified in RFC 5574. In other words, each RTP header
	// is replaced with a single byte containing the block length. Only Speex
	// wideband is supported. `sample_rate_hertz` must be 16000.
	AudioEncoding_AUDIO_ENCODING_SPEEX_WITH_HEADER_BYTE AudioEncoding = 7
)

var AudioEncoding_name = map[int32]string{
	0: "AUDIO_ENCODING_UNSPECIFIED",
	1: "AUDIO_ENCODING_LINEAR_16",
	2: "AUDIO_ENCODING_FLAC",
	3: "AUDIO_ENCODING_MULAW",
	4: "AUDIO_ENCODING_AMR",
	5: "AUDIO_ENCODING_AMR_WB",
	6: "AUDIO_ENCODING_OGG_OPUS",
	7: "AUDIO_ENCODING_SPEEX_WITH_HEADER_BYTE",
}
var AudioEncoding_value = map[string]int32{
	"AUDIO_ENCODING_UNSPECIFIED":            0,
	"AUDIO_ENCODING_LINEAR_16":              1,
	"AUDIO_ENCODING_FLAC":                   2,
	"AUDIO_ENCODING_MULAW":                  3,
	"AUDIO_ENCODING_AMR":                    4,
	"AUDIO_ENCODING_AMR_WB":                 5,
	"AUDIO_ENCODING_OGG_OPUS":               6,
	"AUDIO_ENCODING_SPEEX_WITH_HEADER_BYTE": 7,
}

func (x AudioEncoding) String() string {
	return proto.EnumName(AudioEncoding_name, int32(x))
}
func (AudioEncoding) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Type of the response message.
type StreamingRecognitionResult_MessageType int32

const (
	// Not specified. Should never be used.
	StreamingRecognitionResult_MESSAGE_TYPE_UNSPECIFIED StreamingRecognitionResult_MessageType = 0
	// Message contains a (possibly partial) transcript.
	StreamingRecognitionResult_TRANSCRIPT StreamingRecognitionResult_MessageType = 1
	// Event indicates that the server has detected the end of the user's speech
	// utterance and expects no additional speech. Therefore, the server will
	// not process additional audio (although it may subsequently return
	// additional results). The client should stop sending additional audio
	// data, half-close the gRPC connection, and wait for any additional results
	// until the server closes the gRPC connection. This message is only sent if
	// `single_utterance` was set to `true`, and is not used otherwise.
	StreamingRecognitionResult_END_OF_SINGLE_UTTERANCE StreamingRecognitionResult_MessageType = 2
)

var StreamingRecognitionResult_MessageType_name = map[int32]string{
	0: "MESSAGE_TYPE_UNSPECIFIED",
	1: "TRANSCRIPT",
	2: "END_OF_SINGLE_UTTERANCE",
}
var StreamingRecognitionResult_MessageType_value = map[string]int32{
	"MESSAGE_TYPE_UNSPECIFIED": 0,
	"TRANSCRIPT":               1,
	"END_OF_SINGLE_UTTERANCE":  2,
}

func (x StreamingRecognitionResult_MessageType) String() string {
	return proto.EnumName(StreamingRecognitionResult_MessageType_name, int32(x))
}
func (StreamingRecognitionResult_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 0}
}

// The request to detect user's intent.
type DetectIntentRequest struct {
	// Required. The name of the session this query is sent to. Format:
	// `projects/<Project ID>/agent/sessions/<Session ID>`.
	// It's up to the API caller to choose an appropriate session ID. It can be
	// a random number or some type of user identifier (preferably hashed).
	// The length of the session ID must not exceed 36 bytes.
	Session string `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	// Optional. The parameters of this query.
	QueryParams *QueryParameters `protobuf:"bytes,2,opt,name=query_params,json=queryParams" json:"query_params,omitempty"`
	// Required. The input specification. It can be set to:
	//
	// 1.  an audio config
	//     which instructs the speech recognizer how to process the speech audio,
	//
	// 2.  a conversational query in the form of text, or
	//
	// 3.  an event that specifies which intent to trigger.
	QueryInput *QueryInput `protobuf:"bytes,3,opt,name=query_input,json=queryInput" json:"query_input,omitempty"`
	// Optional. The natural language speech audio to be processed. This field
	// should be populated iff `query_input` is set to an input audio config.
	// A single request can contain up to 1 minute of speech audio data.
	InputAudio []byte `protobuf:"bytes,5,opt,name=input_audio,json=inputAudio,proto3" json:"input_audio,omitempty"`
}

func (m *DetectIntentRequest) Reset()                    { *m = DetectIntentRequest{} }
func (m *DetectIntentRequest) String() string            { return proto.CompactTextString(m) }
func (*DetectIntentRequest) ProtoMessage()               {}
func (*DetectIntentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DetectIntentRequest) GetQueryParams() *QueryParameters {
	if m != nil {
		return m.QueryParams
	}
	return nil
}

func (m *DetectIntentRequest) GetQueryInput() *QueryInput {
	if m != nil {
		return m.QueryInput
	}
	return nil
}

// The message returned from the DetectIntent method.
type DetectIntentResponse struct {
	// The unique identifier of the response. It can be used to
	// locate a response in the training example set or for reporting issues.
	ResponseId string `protobuf:"bytes,1,opt,name=response_id,json=responseId" json:"response_id,omitempty"`
	// The results of the conversational query or event processing.
	QueryResult *QueryResult `protobuf:"bytes,2,opt,name=query_result,json=queryResult" json:"query_result,omitempty"`
	// Specifies the status of the webhook request. `webhook_status`
	// is never populated in webhook requests.
	WebhookStatus *google_rpc.Status `protobuf:"bytes,3,opt,name=webhook_status,json=webhookStatus" json:"webhook_status,omitempty"`
}

func (m *DetectIntentResponse) Reset()                    { *m = DetectIntentResponse{} }
func (m *DetectIntentResponse) String() string            { return proto.CompactTextString(m) }
func (*DetectIntentResponse) ProtoMessage()               {}
func (*DetectIntentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DetectIntentResponse) GetQueryResult() *QueryResult {
	if m != nil {
		return m.QueryResult
	}
	return nil
}

func (m *DetectIntentResponse) GetWebhookStatus() *google_rpc.Status {
	if m != nil {
		return m.WebhookStatus
	}
	return nil
}

// Represents the parameters of the conversational query.
type QueryParameters struct {
	// Optional. The time zone of this conversational query from the
	// [time zone database](https://www.iana.org/time-zones), e.g.,
	// America/New_York, Europe/Paris. If not provided, the time zone specified in
	// agent settings is used.
	TimeZone string `protobuf:"bytes,1,opt,name=time_zone,json=timeZone" json:"time_zone,omitempty"`
	// Optional. The geo location of this conversational query.
	GeoLocation *google_type.LatLng `protobuf:"bytes,2,opt,name=geo_location,json=geoLocation" json:"geo_location,omitempty"`
	// Optional. The collection of contexts to be activated before this query is
	// executed.
	Contexts []*google_cloud_dialogflow_v2beta1.Context `protobuf:"bytes,3,rep,name=contexts" json:"contexts,omitempty"`
	// Optional. Specifies whether to delete all contexts in the current session
	// before the new ones are activated.
	ResetContexts bool `protobuf:"varint,4,opt,name=reset_contexts,json=resetContexts" json:"reset_contexts,omitempty"`
	// Optional. The collection of session entity types to replace or extend
	// developer entities with for this query only. The entity synonyms apply
	// to all languages.
	SessionEntityTypes []*google_cloud_dialogflow_v2beta13.SessionEntityType `protobuf:"bytes,5,rep,name=session_entity_types,json=sessionEntityTypes" json:"session_entity_types,omitempty"`
	// Optional. This field can be used to pass custom data into the webhook
	// associated with the agent. Arbitrary JSON objects are supported.
	Payload *google_protobuf3.Struct `protobuf:"bytes,6,opt,name=payload" json:"payload,omitempty"`
}

func (m *QueryParameters) Reset()                    { *m = QueryParameters{} }
func (m *QueryParameters) String() string            { return proto.CompactTextString(m) }
func (*QueryParameters) ProtoMessage()               {}
func (*QueryParameters) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryParameters) GetGeoLocation() *google_type.LatLng {
	if m != nil {
		return m.GeoLocation
	}
	return nil
}

func (m *QueryParameters) GetContexts() []*google_cloud_dialogflow_v2beta1.Context {
	if m != nil {
		return m.Contexts
	}
	return nil
}

func (m *QueryParameters) GetSessionEntityTypes() []*google_cloud_dialogflow_v2beta13.SessionEntityType {
	if m != nil {
		return m.SessionEntityTypes
	}
	return nil
}

func (m *QueryParameters) GetPayload() *google_protobuf3.Struct {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Represents the query input. It can contain either:
//
// 1.  an audio config which
//     instructs the speech recognizer how to process the speech audio,
//
// 2.  a conversational query in the form of text, or
//
// 3.  an event that specifies which intent to trigger.
type QueryInput struct {
	// Required. The input specification.
	//
	// Types that are valid to be assigned to Input:
	//	*QueryInput_AudioConfig
	//	*QueryInput_Text
	//	*QueryInput_Event
	Input isQueryInput_Input `protobuf_oneof:"input"`
}

func (m *QueryInput) Reset()                    { *m = QueryInput{} }
func (m *QueryInput) String() string            { return proto.CompactTextString(m) }
func (*QueryInput) ProtoMessage()               {}
func (*QueryInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isQueryInput_Input interface {
	isQueryInput_Input()
}

type QueryInput_AudioConfig struct {
	AudioConfig *InputAudioConfig `protobuf:"bytes,1,opt,name=audio_config,json=audioConfig,oneof"`
}
type QueryInput_Text struct {
	Text *TextInput `protobuf:"bytes,2,opt,name=text,oneof"`
}
type QueryInput_Event struct {
	Event *EventInput `protobuf:"bytes,3,opt,name=event,oneof"`
}

func (*QueryInput_AudioConfig) isQueryInput_Input() {}
func (*QueryInput_Text) isQueryInput_Input()        {}
func (*QueryInput_Event) isQueryInput_Input()       {}

func (m *QueryInput) GetInput() isQueryInput_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *QueryInput) GetAudioConfig() *InputAudioConfig {
	if x, ok := m.GetInput().(*QueryInput_AudioConfig); ok {
		return x.AudioConfig
	}
	return nil
}

func (m *QueryInput) GetText() *TextInput {
	if x, ok := m.GetInput().(*QueryInput_Text); ok {
		return x.Text
	}
	return nil
}

func (m *QueryInput) GetEvent() *EventInput {
	if x, ok := m.GetInput().(*QueryInput_Event); ok {
		return x.Event
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*QueryInput) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _QueryInput_OneofMarshaler, _QueryInput_OneofUnmarshaler, _QueryInput_OneofSizer, []interface{}{
		(*QueryInput_AudioConfig)(nil),
		(*QueryInput_Text)(nil),
		(*QueryInput_Event)(nil),
	}
}

func _QueryInput_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*QueryInput)
	// input
	switch x := m.Input.(type) {
	case *QueryInput_AudioConfig:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AudioConfig); err != nil {
			return err
		}
	case *QueryInput_Text:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Text); err != nil {
			return err
		}
	case *QueryInput_Event:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Event); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("QueryInput.Input has unexpected type %T", x)
	}
	return nil
}

func _QueryInput_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*QueryInput)
	switch tag {
	case 1: // input.audio_config
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InputAudioConfig)
		err := b.DecodeMessage(msg)
		m.Input = &QueryInput_AudioConfig{msg}
		return true, err
	case 2: // input.text
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TextInput)
		err := b.DecodeMessage(msg)
		m.Input = &QueryInput_Text{msg}
		return true, err
	case 3: // input.event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EventInput)
		err := b.DecodeMessage(msg)
		m.Input = &QueryInput_Event{msg}
		return true, err
	default:
		return false, nil
	}
}

func _QueryInput_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*QueryInput)
	// input
	switch x := m.Input.(type) {
	case *QueryInput_AudioConfig:
		s := proto.Size(x.AudioConfig)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueryInput_Text:
		s := proto.Size(x.Text)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueryInput_Event:
		s := proto.Size(x.Event)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Represents the result of conversational query or event processing.
type QueryResult struct {
	// The original conversational query text:
	// - If natural language text was provided as input, `query_text` contains
	//   a copy of the input.
	// - If natural language speech audio was provided as input, `query_text`
	//   contains the speech recognition result. If speech recognizer produced
	//   multiple alternatives, a particular one is picked.
	// - If an event was provided as input, `query_text` is not set.
	QueryText string `protobuf:"bytes,1,opt,name=query_text,json=queryText" json:"query_text,omitempty"`
	// The language that was triggered during intent detection.
	// See [Language Support](https://dialogflow.com/docs/reference/language)
	// for a list of the currently supported language codes.
	LanguageCode string `protobuf:"bytes,15,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
	// The confidence estimate between 0.0 and 1.0. A higher number
	// indicates an estimated greater likelihood that the recognized words are
	// correct. The default of 0.0 is a sentinel value indicating that confidence
	// was not set. This field is populated if natural speech audio was provided
	// as input.
	SpeechRecognitionConfidence float32 `protobuf:"fixed32,2,opt,name=speech_recognition_confidence,json=speechRecognitionConfidence" json:"speech_recognition_confidence,omitempty"`
	// The action name from the matched intent.
	Action string `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
	// The collection of extracted parameters.
	Parameters *google_protobuf3.Struct `protobuf:"bytes,4,opt,name=parameters" json:"parameters,omitempty"`
	// This field is set to:
	// - `false` if the matched intent has required parameters and not all of
	//    the required parameter values have been collected.
	// - `true` if all required parameter values have been collected, or if the
	//    matched intent doesn't contain any required parameters.
	AllRequiredParamsPresent bool `protobuf:"varint,5,opt,name=all_required_params_present,json=allRequiredParamsPresent" json:"all_required_params_present,omitempty"`
	// The text to be pronounced to the user or shown on the screen.
	FulfillmentText string `protobuf:"bytes,6,opt,name=fulfillment_text,json=fulfillmentText" json:"fulfillment_text,omitempty"`
	// The collection of rich messages to present to the user.
	FulfillmentMessages []*google_cloud_dialogflow_v2beta11.Intent_Message `protobuf:"bytes,7,rep,name=fulfillment_messages,json=fulfillmentMessages" json:"fulfillment_messages,omitempty"`
	// If the query was fulfilled by a webhook call, this field is set to the
	// value of the `source` field returned in the webhook response.
	WebhookSource string `protobuf:"bytes,8,opt,name=webhook_source,json=webhookSource" json:"webhook_source,omitempty"`
	// If the query was fulfilled by a webhook call, this field is set to the
	// value of the `payload` field returned in the webhook response.
	WebhookPayload *google_protobuf3.Struct `protobuf:"bytes,9,opt,name=webhook_payload,json=webhookPayload" json:"webhook_payload,omitempty"`
	// The collection of output contexts. If applicable,
	// `output_contexts.parameters` contains entries with name
	// `<parameter name>.original` containing the original parameter values
	// before the query.
	OutputContexts []*google_cloud_dialogflow_v2beta1.Context `protobuf:"bytes,10,rep,name=output_contexts,json=outputContexts" json:"output_contexts,omitempty"`
	// The intent that matched the conversational query. Some, not
	// all fields are filled in this message, including but not limited to:
	// `name`, `display_name` and `webhook_state`.
	Intent *google_cloud_dialogflow_v2beta11.Intent `protobuf:"bytes,11,opt,name=intent" json:"intent,omitempty"`
	// The intent detection confidence. Values range from 0.0
	// (completely uncertain) to 1.0 (completely certain).
	IntentDetectionConfidence float32 `protobuf:"fixed32,12,opt,name=intent_detection_confidence,json=intentDetectionConfidence" json:"intent_detection_confidence,omitempty"`
	// The free-form diagnostic info. For example, this field
	// could contain webhook call latency.
	DiagnosticInfo *google_protobuf3.Struct `protobuf:"bytes,14,opt,name=diagnostic_info,json=diagnosticInfo" json:"diagnostic_info,omitempty"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QueryResult) GetParameters() *google_protobuf3.Struct {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *QueryResult) GetFulfillmentMessages() []*google_cloud_dialogflow_v2beta11.Intent_Message {
	if m != nil {
		return m.FulfillmentMessages
	}
	return nil
}

func (m *QueryResult) GetWebhookPayload() *google_protobuf3.Struct {
	if m != nil {
		return m.WebhookPayload
	}
	return nil
}

func (m *QueryResult) GetOutputContexts() []*google_cloud_dialogflow_v2beta1.Context {
	if m != nil {
		return m.OutputContexts
	}
	return nil
}

func (m *QueryResult) GetIntent() *google_cloud_dialogflow_v2beta11.Intent {
	if m != nil {
		return m.Intent
	}
	return nil
}

func (m *QueryResult) GetDiagnosticInfo() *google_protobuf3.Struct {
	if m != nil {
		return m.DiagnosticInfo
	}
	return nil
}

// The top-level message sent by the client to the
// `StreamingDetectIntent` method.
//
// Multiple request messages should be sent in order:
//
// 1.  The first message must contain `session`, `query_input` plus optionally
//     `query_params` and/or `single_utterance`. The message must not contain `input_audio`.
//
// 2.  If `query_input` was set to a streaming input audio config,
//     all subsequent messages must contain only `input_audio`.
//     Otherwise, finish the request stream.
type StreamingDetectIntentRequest struct {
	// Required. The name of the session the query is sent to.
	// Format of the session name:
	// `projects/<Project ID>/agent/sessions/<Session ID>`.
	// It’s up to the API caller to choose an appropriate <Session ID>. It can be
	// a random number or some type of user identifier (preferably hashed).
	// The length of the session ID must not exceed 36 characters.
	Session string `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	// Optional. The parameters of this query.
	QueryParams *QueryParameters `protobuf:"bytes,2,opt,name=query_params,json=queryParams" json:"query_params,omitempty"`
	// Required. The input specification. It can be set to:
	//
	// 1.  an audio config which instructs the speech recognizer how to process
	//     the speech audio,
	//
	// 2.  a conversational query in the form of text, or
	//
	// 3.  an event that specifies which intent to trigger.
	QueryInput *QueryInput `protobuf:"bytes,3,opt,name=query_input,json=queryInput" json:"query_input,omitempty"`
	// Optional. If `true`, the recognizer will detect a single spoken utterance
	// in input audio. When it detects that the user has paused or stopped
	// speaking, it will cease recognition. This setting is ignored when
	// `query_input` is a piece of text or an event.
	SingleUtterance bool `protobuf:"varint,4,opt,name=single_utterance,json=singleUtterance" json:"single_utterance,omitempty"`
	// Optional. The input audio content to be recognized. Must be sent if
	// `query_input` was set to a streaming input audio config. The complete audio
	// over all streaming messages must not exceed 1 minute.
	InputAudio []byte `protobuf:"bytes,6,opt,name=input_audio,json=inputAudio,proto3" json:"input_audio,omitempty"`
}

func (m *StreamingDetectIntentRequest) Reset()                    { *m = StreamingDetectIntentRequest{} }
func (m *StreamingDetectIntentRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamingDetectIntentRequest) ProtoMessage()               {}
func (*StreamingDetectIntentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StreamingDetectIntentRequest) GetQueryParams() *QueryParameters {
	if m != nil {
		return m.QueryParams
	}
	return nil
}

func (m *StreamingDetectIntentRequest) GetQueryInput() *QueryInput {
	if m != nil {
		return m.QueryInput
	}
	return nil
}

// The top-level message returned from the
// `StreamingDetectIntent` method.
//
// Multiple response messages can be returned in order:
//
// 1.  If the input was set to streaming audio, the first one or more messages
//     contain `recognition_result`. Each `recognition_result` represents a more
//     complete transcript of what the user said. The last `recognition_result`
//     has `is_final` set to `true`.
//
// 2.  The next message contains `response_id`, `query_result`
//     and optionally `webhook_status` if a WebHook was called.
type StreamingDetectIntentResponse struct {
	// The unique identifier of the response. It can be used to
	// locate a response in the training example set or for reporting issues.
	ResponseId string `protobuf:"bytes,1,opt,name=response_id,json=responseId" json:"response_id,omitempty"`
	// The result of speech recognition.
	RecognitionResult *StreamingRecognitionResult `protobuf:"bytes,2,opt,name=recognition_result,json=recognitionResult" json:"recognition_result,omitempty"`
	// The result of the conversational query or event processing.
	QueryResult *QueryResult `protobuf:"bytes,3,opt,name=query_result,json=queryResult" json:"query_result,omitempty"`
	// Specifies the status of the webhook request.
	WebhookStatus *google_rpc.Status `protobuf:"bytes,4,opt,name=webhook_status,json=webhookStatus" json:"webhook_status,omitempty"`
}

func (m *StreamingDetectIntentResponse) Reset()                    { *m = StreamingDetectIntentResponse{} }
func (m *StreamingDetectIntentResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamingDetectIntentResponse) ProtoMessage()               {}
func (*StreamingDetectIntentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StreamingDetectIntentResponse) GetRecognitionResult() *StreamingRecognitionResult {
	if m != nil {
		return m.RecognitionResult
	}
	return nil
}

func (m *StreamingDetectIntentResponse) GetQueryResult() *QueryResult {
	if m != nil {
		return m.QueryResult
	}
	return nil
}

func (m *StreamingDetectIntentResponse) GetWebhookStatus() *google_rpc.Status {
	if m != nil {
		return m.WebhookStatus
	}
	return nil
}

// Contains a speech recognition result corresponding to a portion of the audio
// that is currently being processed or an indication that this is the end
// of the single requested utterance.
//
// Example:
//
// 1.  transcript: "tube"
//
// 2.  transcript: "to be a"
//
// 3.  transcript: "to be"
//
// 4.  transcript: "to be or not to be"
//     is_final: true
//
// 5.  transcript: " that's"
//
// 6.  transcript: " that is"
//
// 7.  recognition_event_type: `RECOGNITION_EVENT_END_OF_SINGLE_UTTERANCE`
//
// 8.  transcript: " that is the question"
//     is_final: true
//
// Only two of the responses contain final results (#4 and #8 indicated by
// `is_final: true`). Concatenating these generates the full transcript: "to be
// or not to be that is the question".
//
// In each response we populate:
//
// *  for `MESSAGE_TYPE_TRANSCRIPT`: `transcript` and possibly `is_final`.
//
// *  for `MESSAGE_TYPE_END_OF_SINGLE_UTTERANCE`: only `event_type`.
type StreamingRecognitionResult struct {
	// Type of the result message.
	MessageType StreamingRecognitionResult_MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,enum=google.cloud.dialogflow.v2beta1.StreamingRecognitionResult_MessageType" json:"message_type,omitempty"`
	// Transcript text representing the words that the user spoke.
	// Populated if and only if `event_type` = `RECOGNITION_EVENT_TRANSCRIPT`.
	Transcript string `protobuf:"bytes,2,opt,name=transcript" json:"transcript,omitempty"`
	// If `false`, the `StreamingRecognitionResult` represents an
	// interim result that may change. If `true`, the recognizer will not return
	// any further hypotheses about this piece of the audio. May only be populated
	// for `event_type` = `RECOGNITION_EVENT_TRANSCRIPT`.
	IsFinal bool `protobuf:"varint,3,opt,name=is_final,json=isFinal" json:"is_final,omitempty"`
}

func (m *StreamingRecognitionResult) Reset()                    { *m = StreamingRecognitionResult{} }
func (m *StreamingRecognitionResult) String() string            { return proto.CompactTextString(m) }
func (*StreamingRecognitionResult) ProtoMessage()               {}
func (*StreamingRecognitionResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// Instructs the speech recognizer how to process the audio content.
type InputAudioConfig struct {
	// Required. Audio encoding of the audio content to process.
	AudioEncoding AudioEncoding `protobuf:"varint,1,opt,name=audio_encoding,json=audioEncoding,enum=google.cloud.dialogflow.v2beta1.AudioEncoding" json:"audio_encoding,omitempty"`
	// Required. Sample rate (in Hertz) of the audio content sent in the query.
	// Refer to [Cloud Speech API documentation](/speech/docs/basics) for more
	// details.
	SampleRateHertz int32 `protobuf:"varint,2,opt,name=sample_rate_hertz,json=sampleRateHertz" json:"sample_rate_hertz,omitempty"`
	// Required. The language of the supplied audio. Dialogflow does not do
	// translations. See [Language
	// Support](https://dialogflow.com/docs/languages) for a list of the
	// currently supported language codes. Note that queries in the same session
	// do not necessarily need to specify the same language.
	LanguageCode string `protobuf:"bytes,3,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
	// Optional. The collection of phrase hints which are used to boost accuracy
	// of speech recognition.
	// Refer to [Cloud Speech API documentation](/speech/docs/basics#phrase-hints)
	// for more details.
	PhraseHints []string `protobuf:"bytes,4,rep,name=phrase_hints,json=phraseHints" json:"phrase_hints,omitempty"`
}

func (m *InputAudioConfig) Reset()                    { *m = InputAudioConfig{} }
func (m *InputAudioConfig) String() string            { return proto.CompactTextString(m) }
func (*InputAudioConfig) ProtoMessage()               {}
func (*InputAudioConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// Represents the natural language text to be processed.
type TextInput struct {
	// Required. The UTF-8 encoded natural language text to be processed.
	// Text length must not exceed 256 bytes.
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	// Required. The language of this conversational query. See [Language
	// Support](https://dialogflow.com/docs/languages) for a list of the
	// currently supported language codes. Note that queries in the same session
	// do not necessarily need to specify the same language.
	LanguageCode string `protobuf:"bytes,2,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
}

func (m *TextInput) Reset()                    { *m = TextInput{} }
func (m *TextInput) String() string            { return proto.CompactTextString(m) }
func (*TextInput) ProtoMessage()               {}
func (*TextInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// Events allow for matching intents by event name instead of the natural
// language input. For instance, input `<event: { name: “welcome_event”,
// parameters: { name: “Sam” } }>` can trigger a personalized welcome response.
// The parameter `name` may be used by the agent in the response:
// `“Hello #welcome_event.name! What can I do for you today?”`.
type EventInput struct {
	// Required. The unique identifier of the event.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Optional. The collection of parameters associated with the event.
	Parameters *google_protobuf3.Struct `protobuf:"bytes,2,opt,name=parameters" json:"parameters,omitempty"`
	// Required. The language of this query. See [Language
	// Support](https://dialogflow.com/docs/languages) for a list of the
	// currently supported language codes. Note that queries in the same session
	// do not necessarily need to specify the same language.
	LanguageCode string `protobuf:"bytes,3,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
}

func (m *EventInput) Reset()                    { *m = EventInput{} }
func (m *EventInput) String() string            { return proto.CompactTextString(m) }
func (*EventInput) ProtoMessage()               {}
func (*EventInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *EventInput) GetParameters() *google_protobuf3.Struct {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func init() {
	proto.RegisterType((*DetectIntentRequest)(nil), "google.cloud.dialogflow.v2beta1.DetectIntentRequest")
	proto.RegisterType((*DetectIntentResponse)(nil), "google.cloud.dialogflow.v2beta1.DetectIntentResponse")
	proto.RegisterType((*QueryParameters)(nil), "google.cloud.dialogflow.v2beta1.QueryParameters")
	proto.RegisterType((*QueryInput)(nil), "google.cloud.dialogflow.v2beta1.QueryInput")
	proto.RegisterType((*QueryResult)(nil), "google.cloud.dialogflow.v2beta1.QueryResult")
	proto.RegisterType((*StreamingDetectIntentRequest)(nil), "google.cloud.dialogflow.v2beta1.StreamingDetectIntentRequest")
	proto.RegisterType((*StreamingDetectIntentResponse)(nil), "google.cloud.dialogflow.v2beta1.StreamingDetectIntentResponse")
	proto.RegisterType((*StreamingRecognitionResult)(nil), "google.cloud.dialogflow.v2beta1.StreamingRecognitionResult")
	proto.RegisterType((*InputAudioConfig)(nil), "google.cloud.dialogflow.v2beta1.InputAudioConfig")
	proto.RegisterType((*TextInput)(nil), "google.cloud.dialogflow.v2beta1.TextInput")
	proto.RegisterType((*EventInput)(nil), "google.cloud.dialogflow.v2beta1.EventInput")
	proto.RegisterEnum("google.cloud.dialogflow.v2beta1.AudioEncoding", AudioEncoding_name, AudioEncoding_value)
	proto.RegisterEnum("google.cloud.dialogflow.v2beta1.StreamingRecognitionResult_MessageType", StreamingRecognitionResult_MessageType_name, StreamingRecognitionResult_MessageType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Sessions service

type SessionsClient interface {
	// Processes a natural language query and returns structured, actionable data
	// as a result. This method is not idempotent, because it may cause contexts
	// and session entity types to be updated, which in turn might affect
	// results of future queries.
	DetectIntent(ctx context.Context, in *DetectIntentRequest, opts ...grpc.CallOption) (*DetectIntentResponse, error)
	// Processes a natural language query in audio format in a streaming fashion
	// and returns structured, actionable data as a result. This method is only
	// available via the gRPC API (not REST).
	StreamingDetectIntent(ctx context.Context, opts ...grpc.CallOption) (Sessions_StreamingDetectIntentClient, error)
}

type sessionsClient struct {
	cc *grpc.ClientConn
}

func NewSessionsClient(cc *grpc.ClientConn) SessionsClient {
	return &sessionsClient{cc}
}

func (c *sessionsClient) DetectIntent(ctx context.Context, in *DetectIntentRequest, opts ...grpc.CallOption) (*DetectIntentResponse, error) {
	out := new(DetectIntentResponse)
	err := grpc.Invoke(ctx, "/google.cloud.dialogflow.v2beta1.Sessions/DetectIntent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) StreamingDetectIntent(ctx context.Context, opts ...grpc.CallOption) (Sessions_StreamingDetectIntentClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Sessions_serviceDesc.Streams[0], c.cc, "/google.cloud.dialogflow.v2beta1.Sessions/StreamingDetectIntent", opts...)
	if err != nil {
		return nil, err
	}
	x := &sessionsStreamingDetectIntentClient{stream}
	return x, nil
}

type Sessions_StreamingDetectIntentClient interface {
	Send(*StreamingDetectIntentRequest) error
	Recv() (*StreamingDetectIntentResponse, error)
	grpc.ClientStream
}

type sessionsStreamingDetectIntentClient struct {
	grpc.ClientStream
}

func (x *sessionsStreamingDetectIntentClient) Send(m *StreamingDetectIntentRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sessionsStreamingDetectIntentClient) Recv() (*StreamingDetectIntentResponse, error) {
	m := new(StreamingDetectIntentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Sessions service

type SessionsServer interface {
	// Processes a natural language query and returns structured, actionable data
	// as a result. This method is not idempotent, because it may cause contexts
	// and session entity types to be updated, which in turn might affect
	// results of future queries.
	DetectIntent(context.Context, *DetectIntentRequest) (*DetectIntentResponse, error)
	// Processes a natural language query in audio format in a streaming fashion
	// and returns structured, actionable data as a result. This method is only
	// available via the gRPC API (not REST).
	StreamingDetectIntent(Sessions_StreamingDetectIntentServer) error
}

func RegisterSessionsServer(s *grpc.Server, srv SessionsServer) {
	s.RegisterService(&_Sessions_serviceDesc, srv)
}

func _Sessions_DetectIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).DetectIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.dialogflow.v2beta1.Sessions/DetectIntent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).DetectIntent(ctx, req.(*DetectIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_StreamingDetectIntent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SessionsServer).StreamingDetectIntent(&sessionsStreamingDetectIntentServer{stream})
}

type Sessions_StreamingDetectIntentServer interface {
	Send(*StreamingDetectIntentResponse) error
	Recv() (*StreamingDetectIntentRequest, error)
	grpc.ServerStream
}

type sessionsStreamingDetectIntentServer struct {
	grpc.ServerStream
}

func (x *sessionsStreamingDetectIntentServer) Send(m *StreamingDetectIntentResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sessionsStreamingDetectIntentServer) Recv() (*StreamingDetectIntentRequest, error) {
	m := new(StreamingDetectIntentRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Sessions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.cloud.dialogflow.v2beta1.Sessions",
	HandlerType: (*SessionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectIntent",
			Handler:    _Sessions_DetectIntent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingDetectIntent",
			Handler:       _Sessions_StreamingDetectIntent_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "session.proto",
}

func init() { proto.RegisterFile("session.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1572 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0x4f, 0x73, 0x1b, 0xb7,
	0x15, 0xf7, 0x52, 0xd6, 0xbf, 0x47, 0x4a, 0x62, 0x60, 0x27, 0x5e, 0x4b, 0x76, 0xec, 0x32, 0x93,
	0x29, 0xad, 0xa6, 0x64, 0xac, 0xb6, 0xe9, 0x24, 0x1e, 0xa7, 0xa6, 0xc8, 0x95, 0xc4, 0x19, 0x9a,
	0x62, 0x40, 0x2a, 0x4e, 0x72, 0xc1, 0x40, 0x4b, 0x70, 0xb5, 0xee, 0x12, 0x58, 0x2d, 0xc0, 0x24,
	0x4a, 0xa7, 0x3d, 0xf4, 0x2b, 0xf4, 0xd6, 0x99, 0x5e, 0x7a, 0xe9, 0x4c, 0xae, 0xbd, 0xf4, 0x9e,
	0x8f, 0xd0, 0x73, 0x6f, 0x3d, 0xb6, 0xa7, 0xf6, 0xd0, 0x99, 0x5e, 0x3a, 0x0b, 0x60, 0x49, 0x9a,
	0x92, 0x43, 0xba, 0xed, 0x29, 0xb7, 0xc5, 0x7b, 0xef, 0xf7, 0xf0, 0xde, 0xc3, 0x0f, 0xef, 0x61,
	0x61, 0x43, 0x32, 0x29, 0x43, 0xc1, 0x2b, 0x71, 0x22, 0x94, 0x40, 0xf7, 0x02, 0x21, 0x82, 0x88,
	0x55, 0xfc, 0x48, 0x8c, 0xfa, 0x95, 0x7e, 0x48, 0x23, 0x11, 0x0c, 0x22, 0xf1, 0x45, 0xe5, 0xf3,
	0xbd, 0x53, 0xa6, 0xe8, 0xc3, 0xed, 0x3b, 0xc6, 0xa0, 0x4a, 0xe3, 0xb0, 0x4a, 0x39, 0x17, 0x8a,
	0xaa, 0x50, 0x70, 0x69, 0xe0, 0xdb, 0x3f, 0xb4, 0x5a, 0x0d, 0xaf, 0x4e, 0xe0, 0x55, 0x0b, 0xaf,
	0xfa, 0x82, 0x2b, 0xf6, 0xa5, 0xb2, 0xe6, 0xef, 0xcc, 0x33, 0x0f, 0xb9, 0x62, 0x3c, 0xb3, 0x7e,
	0x7f, 0x9e, 0xb5, 0x4d, 0x85, 0x30, 0xae, 0x42, 0x75, 0x41, 0xd4, 0x45, 0xcc, 0x2c, 0x34, 0x8b,
	0x5a, 0xaf, 0x4e, 0x47, 0x83, 0xaa, 0x54, 0xc9, 0xc8, 0xcf, 0x1c, 0xdf, 0xb2, 0xda, 0x24, 0xf6,
	0xab, 0x52, 0x51, 0x35, 0xca, 0xd2, 0x71, 0xad, 0x22, 0xf5, 0x54, 0x8d, 0xa8, 0x8a, 0x78, 0x60,
	0x34, 0xa5, 0x7f, 0x38, 0x70, 0xa3, 0xc1, 0x14, 0xf3, 0x55, 0x53, 0x87, 0x88, 0xd9, 0xf9, 0x88,
	0x49, 0x85, 0x5c, 0x58, 0xb5, 0x51, 0xb8, 0xce, 0x7d, 0xa7, 0xbc, 0x8e, 0xb3, 0x25, 0xea, 0x42,
	0xe1, 0x7c, 0xc4, 0x92, 0x0b, 0x12, 0xd3, 0x84, 0x0e, 0xa5, 0x9b, 0xbb, 0xef, 0x94, 0xf3, 0x7b,
	0xef, 0x56, 0xe6, 0x14, 0xbc, 0xf2, 0x51, 0x0a, 0xea, 0xa4, 0x18, 0xa6, 0x58, 0x22, 0x71, 0xfe,
	0x7c, 0x2c, 0x90, 0xa8, 0x05, 0x66, 0x49, 0x42, 0x1e, 0x8f, 0x94, 0xbb, 0xa4, 0x7d, 0xfe, 0x60,
	0x31, 0x9f, 0xcd, 0x14, 0x82, 0xe1, 0x7c, 0xfc, 0x8d, 0xee, 0x41, 0x5e, 0xfb, 0x21, 0x74, 0xd4,
	0x0f, 0x85, 0xbb, 0x7c, 0xdf, 0x29, 0x17, 0x30, 0x68, 0x51, 0x2d, 0x95, 0x94, 0xbe, 0x71, 0xe0,
	0xe6, 0x8b, 0x59, 0xcb, 0x58, 0x70, 0xc9, 0x52, 0x64, 0x62, 0xbf, 0x49, 0xd8, 0xb7, 0xa9, 0x43,
	0x26, 0x6a, 0xf6, 0xd1, 0x71, 0x96, 0x7d, 0xc2, 0xe4, 0x28, 0x52, 0x36, 0xfb, 0x77, 0x16, 0x8b,
	0x14, 0x6b, 0x8c, 0xcd, 0xdc, 0x2c, 0xd0, 0xfb, 0xb0, 0xf9, 0x05, 0x3b, 0x3d, 0x13, 0xe2, 0xe7,
	0xc4, 0x1c, 0x99, 0x4d, 0x1e, 0x65, 0x2e, 0x93, 0xd8, 0xaf, 0x74, 0xb5, 0x06, 0x6f, 0x58, 0x4b,
	0xb3, 0x2c, 0xfd, 0x2d, 0x07, 0x5b, 0x33, 0x55, 0x45, 0x3b, 0xb0, 0xae, 0xc2, 0x21, 0x23, 0x5f,
	0x09, 0xce, 0x6c, 0xf8, 0x6b, 0xa9, 0xe0, 0x33, 0xc1, 0x19, 0x7a, 0x0f, 0x0a, 0x01, 0x13, 0x24,
	0x12, 0xbe, 0x26, 0xbb, 0x0d, 0xfe, 0x46, 0xb6, 0x93, 0xe6, 0x59, 0x8b, 0xaa, 0x16, 0x0f, 0x70,
	0x3e, 0x60, 0xa2, 0x65, 0xed, 0x50, 0x03, 0xd6, 0x2c, 0xdf, 0xd3, 0xe8, 0x96, 0xca, 0xf9, 0xbd,
	0xf2, 0xdc, 0x84, 0xeb, 0x06, 0x80, 0xc7, 0x48, 0xf4, 0x36, 0x6c, 0x26, 0x4c, 0x32, 0x45, 0xc6,
	0xbe, 0xae, 0xdf, 0x77, 0xca, 0x6b, 0x78, 0x43, 0x4b, 0xeb, 0x99, 0x59, 0x1f, 0x6e, 0x5e, 0xc1,
	0x7f, 0xe9, 0x2e, 0xeb, 0x8d, 0xf7, 0xe6, 0x6e, 0xdc, 0x35, 0x60, 0x4f, 0x63, 0x7b, 0x17, 0x31,
	0xc3, 0x48, 0xce, 0x8a, 0x24, 0x7a, 0x08, 0xab, 0x31, 0xbd, 0x88, 0x04, 0xed, 0xbb, 0x2b, 0xba,
	0x0a, 0xb7, 0x32, 0xc7, 0xd9, 0xd5, 0xaa, 0x74, 0xf5, 0xd5, 0xc2, 0x99, 0x5d, 0xe9, 0x9f, 0x0e,
	0xc0, 0x84, 0x70, 0xe8, 0x63, 0x28, 0x68, 0x7a, 0xa5, 0xe9, 0x0c, 0xc2, 0x40, 0x17, 0x3b, 0xbf,
	0xf7, 0x70, 0x6e, 0x7c, 0xcd, 0x31, 0x0d, 0xeb, 0x1a, 0x78, 0x74, 0x0d, 0xe7, 0xe9, 0x64, 0x89,
	0x9e, 0xc0, 0xf5, 0xb4, 0x10, 0xf6, 0x70, 0x76, 0xe7, 0xfa, 0xeb, 0xb1, 0x2f, 0x95, 0xf6, 0x79,
	0x74, 0x0d, 0x6b, 0x24, 0xaa, 0xc3, 0x32, 0xfb, 0x9c, 0xf1, 0xc5, 0xaf, 0x91, 0x97, 0x5a, 0x67,
	0x3e, 0x0c, 0x76, 0x7f, 0x15, 0x96, 0xf5, 0x85, 0x29, 0xfd, 0x71, 0x05, 0xf2, 0x53, 0xec, 0x45,
	0x77, 0xc1, 0x5c, 0x35, 0xa2, 0xa3, 0x34, 0x14, 0x5b, 0xd7, 0x92, 0x34, 0x12, 0xf4, 0x16, 0x6c,
	0x44, 0x94, 0x07, 0x23, 0x1a, 0x30, 0xe2, 0x8b, 0x3e, 0x73, 0xb7, 0xb4, 0x45, 0x21, 0x13, 0xd6,
	0x45, 0x9f, 0xa1, 0x7d, 0xb8, 0x2b, 0x63, 0xc6, 0xfc, 0x33, 0x92, 0x30, 0x5f, 0x04, 0x3c, 0x4c,
	0x69, 0x66, 0x0a, 0xd9, 0x67, 0xdc, 0x67, 0x3a, 0xf9, 0x1c, 0xde, 0x31, 0x46, 0x78, 0x62, 0x53,
	0x1f, 0x9b, 0xa0, 0x37, 0x60, 0x85, 0xfa, 0x9a, 0xc6, 0x4b, 0x7a, 0x07, 0xbb, 0x42, 0x3f, 0x05,
	0x88, 0xc7, 0xf7, 0x41, 0x53, 0xec, 0x5b, 0x0e, 0x77, 0xca, 0x14, 0x3d, 0x86, 0x1d, 0x1a, 0x45,
	0x24, 0x61, 0xe7, 0xa3, 0x30, 0x61, 0x7d, 0xdb, 0xdf, 0x48, 0x9c, 0xd2, 0x93, 0x2b, 0xdd, 0x45,
	0xd6, 0xb0, 0x4b, 0xa3, 0x08, 0x5b, 0x0b, 0xd3, 0xbb, 0x3a, 0x46, 0x8f, 0x1e, 0x40, 0x71, 0x30,
	0x8a, 0x06, 0x61, 0x14, 0x0d, 0x19, 0x57, 0xa6, 0x3a, 0x2b, 0x3a, 0xb2, 0xad, 0x29, 0xb9, 0xae,
	0xd1, 0x29, 0xdc, 0x9c, 0x36, 0x1d, 0x32, 0x29, 0x69, 0xc0, 0xa4, 0xbb, 0xaa, 0x29, 0x5e, 0x5d,
	0x80, 0x42, 0x7a, 0x9a, 0x3c, 0x35, 0x38, 0x7c, 0x63, 0xca, 0x99, 0x95, 0xe9, 0xdb, 0x36, 0xee,
	0x2b, 0x62, 0x94, 0xf8, 0xcc, 0x5d, 0xd3, 0xc1, 0x8c, 0x7b, 0x88, 0x16, 0xa2, 0x27, 0xb0, 0x95,
	0x99, 0x65, 0xf7, 0x61, 0xfd, 0xdb, 0x4b, 0x96, 0xb9, 0xed, 0x18, 0x73, 0xf4, 0x11, 0x6c, 0x89,
	0x91, 0x4a, 0xbb, 0xed, 0xf8, 0x5e, 0xc3, 0x2b, 0xf6, 0x88, 0x4d, 0xe3, 0x60, 0xdc, 0x02, 0x7e,
	0x06, 0x2b, 0x66, 0x60, 0xba, 0x79, 0x1d, 0xcb, 0xf7, 0x17, 0xac, 0x08, 0xb6, 0x30, 0xf4, 0x21,
	0xec, 0x98, 0x2f, 0xd2, 0xd7, 0x5d, 0x7e, 0x86, 0x5d, 0x05, 0xcd, 0xae, 0xdb, 0xc6, 0xa4, 0x91,
	0x59, 0x4c, 0x71, 0xeb, 0x09, 0x6c, 0xf5, 0x43, 0x1a, 0x70, 0x21, 0x55, 0xe8, 0x93, 0x90, 0x0f,
	0x84, 0xbb, 0x39, 0xa7, 0x2a, 0x13, 0xfb, 0x26, 0x1f, 0x88, 0xd2, 0x1f, 0x72, 0x70, 0xa7, 0xab,
	0x12, 0x46, 0x87, 0x21, 0x0f, 0xbe, 0x73, 0x03, 0xf6, 0x01, 0x14, 0x65, 0xc8, 0x83, 0x88, 0x91,
	0x91, 0x52, 0x2c, 0xa1, 0x69, 0x51, 0x4d, 0x33, 0xdf, 0x32, 0xf2, 0x93, 0x4c, 0x3c, 0x3b, 0x8b,
	0x57, 0x2e, 0xcd, 0xe2, 0x3f, 0xe5, 0xe0, 0xee, 0x4b, 0x2a, 0xb5, 0xe8, 0x50, 0x7e, 0x0e, 0x68,
	0xba, 0x8f, 0xbc, 0x30, 0x9a, 0x1f, 0xcd, 0x1f, 0x18, 0xd9, 0xe6, 0x53, 0x7d, 0xc6, 0x4e, 0xea,
	0xd7, 0x92, 0x59, 0xd1, 0xa5, 0x07, 0xc0, 0xd2, 0xff, 0xff, 0x01, 0x70, 0x7d, 0xd1, 0x07, 0xc0,
	0xef, 0x72, 0xb0, 0xfd, 0xf2, 0xe8, 0xd1, 0x73, 0x28, 0xd8, 0xd6, 0xa2, 0x47, 0xa8, 0x2e, 0xdc,
	0xe6, 0xde, 0xe1, 0xff, 0x50, 0x90, 0xac, 0xe5, 0xe8, 0xb1, 0x9a, 0x1f, 0x4e, 0x16, 0xe8, 0x4d,
	0x00, 0x95, 0x50, 0x2e, 0xfd, 0x24, 0x8c, 0x4d, 0xe9, 0xd7, 0xf1, 0x94, 0x04, 0xdd, 0x86, 0xb5,
	0x50, 0x92, 0x41, 0xc8, 0x69, 0xa4, 0x4b, 0xb6, 0x86, 0x57, 0x43, 0x79, 0x90, 0x2e, 0x4b, 0x9f,
	0x40, 0x7e, 0xca, 0x2d, 0xba, 0x03, 0xee, 0x53, 0xaf, 0xdb, 0xad, 0x1d, 0x7a, 0xa4, 0xf7, 0x69,
	0xc7, 0x23, 0x27, 0xed, 0x6e, 0xc7, 0xab, 0x37, 0x0f, 0x9a, 0x5e, 0xa3, 0x78, 0x0d, 0x6d, 0x02,
	0xf4, 0x70, 0xad, 0xdd, 0xad, 0xe3, 0x66, 0xa7, 0x57, 0x74, 0xd0, 0x0e, 0xdc, 0xf2, 0xda, 0x0d,
	0x72, 0x7c, 0x40, 0xba, 0xcd, 0xf6, 0x61, 0xcb, 0x23, 0x27, 0xbd, 0x9e, 0x87, 0x6b, 0xed, 0xba,
	0x57, 0xcc, 0x95, 0xfe, 0xe2, 0x40, 0x71, 0x76, 0xdc, 0xa2, 0x13, 0xd8, 0x34, 0x73, 0x9b, 0x71,
	0x5f, 0xf4, 0x43, 0x1e, 0xd8, 0xba, 0x54, 0xe6, 0xd6, 0x45, 0x7b, 0xf1, 0x2c, 0x0a, 0x6f, 0xd0,
	0xe9, 0x25, 0xda, 0x85, 0xd7, 0x24, 0x1d, 0xc6, 0x11, 0x23, 0x09, 0x55, 0x8c, 0x9c, 0xb1, 0x44,
	0x7d, 0xa5, 0xeb, 0xb0, 0x8c, 0xb7, 0x8c, 0x02, 0x53, 0xc5, 0x8e, 0x52, 0xf1, 0xe5, 0x19, 0xb9,
	0x74, 0xc5, 0x8c, 0xfc, 0x1e, 0x14, 0xe2, 0xb3, 0x84, 0x4a, 0x46, 0xce, 0x42, 0xae, 0x1f, 0x4b,
	0x4b, 0xe5, 0x75, 0x9c, 0x37, 0xb2, 0xa3, 0x54, 0x54, 0x6a, 0xc0, 0xfa, 0x78, 0xfa, 0x23, 0x64,
	0xdf, 0x0d, 0xe6, 0x7a, 0x98, 0x97, 0xc0, 0xa5, 0x8d, 0x72, 0x97, 0x37, 0x2a, 0xfd, 0x0a, 0x60,
	0xf2, 0x00, 0x48, 0xdd, 0x70, 0x3a, 0xcc, 0xde, 0x8e, 0xfa, 0x7b, 0x66, 0xa4, 0xe6, 0x16, 0x1f,
	0xa9, 0x8b, 0x24, 0xba, 0xfb, 0x6f, 0x07, 0x36, 0x5e, 0x28, 0x2d, 0x7a, 0x13, 0xb6, 0x6b, 0x27,
	0x8d, 0xe6, 0x31, 0xf1, 0xda, 0xf5, 0xe3, 0x46, 0xb3, 0x7d, 0x38, 0x43, 0x82, 0x3b, 0xe0, 0xce,
	0xe8, 0x5b, 0xcd, 0xb6, 0x57, 0xc3, 0xe4, 0xe1, 0x7b, 0x45, 0x07, 0xdd, 0x82, 0x1b, 0x33, 0xda,
	0x83, 0x56, 0xad, 0x5e, 0xcc, 0x21, 0x17, 0x6e, 0xce, 0x28, 0x9e, 0x9e, 0xb4, 0x6a, 0xcf, 0x8a,
	0x4b, 0xe8, 0x0d, 0x40, 0x33, 0x9a, 0xda, 0x53, 0x5c, 0xbc, 0x8e, 0x6e, 0xc3, 0xeb, 0x97, 0xe5,
	0xe4, 0xd9, 0x7e, 0x71, 0x39, 0x25, 0xde, 0x8c, 0xea, 0xf8, 0xf0, 0x90, 0x1c, 0x77, 0x4e, 0xba,
	0xc5, 0x15, 0xf4, 0x00, 0xde, 0x9e, 0x51, 0x76, 0x3b, 0x9e, 0xf7, 0x09, 0x79, 0xd6, 0xec, 0x1d,
	0x91, 0x23, 0xaf, 0xd6, 0xf0, 0x30, 0xd9, 0xff, 0xb4, 0xe7, 0x15, 0x57, 0xf7, 0xfe, 0x9e, 0x83,
	0x35, 0xfb, 0x64, 0x95, 0xe8, 0x1b, 0x07, 0x0a, 0xd3, 0x2d, 0x10, 0xfd, 0x78, 0x2e, 0x29, 0xaf,
	0x98, 0x2d, 0xdb, 0x3f, 0x79, 0x45, 0x94, 0x69, 0xa4, 0xa5, 0x83, 0x5f, 0xff, 0xf9, 0xaf, 0xbf,
	0xc9, 0x3d, 0x29, 0x3d, 0x1a, 0xff, 0x88, 0xfe, 0xc2, 0xce, 0xa4, 0xc7, 0x71, 0x22, 0x9e, 0x33,
	0x5f, 0xc9, 0xea, 0x6e, 0x95, 0x06, 0x8c, 0xab, 0xec, 0x17, 0x55, 0x56, 0x77, 0x7f, 0xf9, 0x41,
	0x7f, 0xca, 0xd9, 0x07, 0xce, 0x2e, 0xfa, 0xad, 0x03, 0xaf, 0x5f, 0xd9, 0xd1, 0xd1, 0xe3, 0xc5,
	0x7b, 0xcf, 0x55, 0x79, 0x7d, 0xf8, 0xdf, 0xc2, 0x4d, 0x82, 0x65, 0xe7, 0x5d, 0x67, 0xff, 0x6b,
	0x07, 0xde, 0xf2, 0xc5, 0x70, 0x9e, 0xa7, 0xfd, 0x82, 0x3d, 0x94, 0x4e, 0x4a, 0xef, 0x8e, 0xf3,
	0x59, 0xd3, 0x02, 0x02, 0x91, 0x92, 0xb7, 0x22, 0x92, 0xa0, 0x1a, 0x30, 0xae, 0xc9, 0x5f, 0x35,
	0x2a, 0x1a, 0x87, 0xf2, 0xa5, 0xff, 0xf4, 0x8f, 0x26, 0xa2, 0x7f, 0x39, 0xce, 0xef, 0x73, 0xb9,
	0xc6, 0xc1, 0xd7, 0xb9, 0x7b, 0x87, 0xc6, 0x67, 0x5d, 0x07, 0xd1, 0x98, 0x04, 0xf1, 0xb1, 0x01,
	0x9d, 0xae, 0x68, 0xff, 0x3f, 0xfa, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0x83, 0xd3, 0x17,
	0xdd, 0x10, 0x00, 0x00,
}
